### ISSUE TITLE
Create a Tiller service account when used with -ns-override

### ISSUE THREAD

**Issue by cogfor** [Praqma/helmsman#116]
We are using namespaces to distinguish between customers. The idea is to use `-ns-override` to specify the customer which would then install Tiller with serviceaccount in that new namespace. Unfortunately, it doesn't seem to work that way.

Example config:

```toml
[namespaces]
  # prevent Tiller from being deployed into kube-system
  [namespaces.kube-system]
  [namespaces.dev]
    installTiller = true

[helmRepos]
  bitnami = "https://charts.bitnami.com/bitnami"

[apps]
  [apps.nginx]
    chart = "bitnami/nginx"
    enabled = true
    name = "nginx"
    namespace = "dev"
    version = "1.1.1"
    wait = true
```

Executing `helmsman -f dsf.toml   --ns-override mycustomer` results in Tiller and service account being created in `dev`, but not in `mycustomer`. 

Moreover, repeating this for the next customer will complain about an already existing nginx release.

Any ideas on how to deal with this use case?
