### ISSUE TITLE
true values will always win when merging DSFs

### ISSUE THREAD

**Issue by knutjda** [Praqma/helmsman#137]
When passing multiple DSFs with the -f option, the DSF with a field containing a true value will always override other values. No matter the order of DSFs. 

Given the following DSFs
*common.yaml:*
```yaml
apps:
  jenkins:
    chart: "stable/jenkins"
    version: "0.21.0"
    enabled: false 
    test: true 
```

*override.yaml:*
```yaml
apps:
  jenkins:
    chart: "stable/jenkins"
    version: "0.21.0"
    enabled: true 
    test: false
```

When I run the following commands 
```bash
helmsman -f common.yaml -f override.yaml -debug
helmsman -f override.yaml -f common.yaml -debug
```

Both commands will output:
```
Applications: 
--------------- 

	chart :  stable/jenkins
	version :  0.21.0
	test :  true
	enabled :  true
```

Probably related to this issue in mergo: https://github.com/imdario/mergo/issues/89

Tested with Helmsman version 1.7.1.
