### ISSUE TITLE
Application should exit when env vars are not set

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [Praqma/helmsman#149]
Hello,

It would be nice to have additional cli switch, or configuration option - to prohibit running helmsman without all environment variables set.

For example:

```
apps:
  xxx-production:
    namespace: default
    enabled: true
    chart: xxx
    version: "0.1.2"
    name: prod
    valuesFiles:
      - "./values-common.yaml"
      - "./values-production.yaml"
    set:
      "image.tag": "$TAG_TO_DEPLOY"
      "image.repository": "$CONTAINER_REGISTRY"
```

Even without setting essential environment variables (tag / repository), helm chart is still applied, with empty "tag" and "repository".
