### ISSUE TITLE
support creating kube context using a bearer token to allow helmsman to run inside clusters. 

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/helmsman#167]
This originates from #107

As some users use CI/CD services inside the cluster, it is useful to allow the kube context created by helmsman to be defined using bearer tokens which can be extracted from a pod's service account. This will allow users to define the context with the kubernetes API service name as the server URI and (optionally) set a path for a bearer token inside the pod where helmsman runs.

The context config in helmsman DSF might look like:

```toml
[settings]
  kubeContext = "internal" 
  clusterURI = "https://kubernetes.default" 
  bearerToken = true
  bearerTokenPath = "/var/run/secrets/kubernetes.io/serviceaccount/token" # optional if a token is provided by the user in another location
```
