### ISSUE TITLE
Certs not removed after helmsman runs

### ISSUE THREAD

**Issue by regner** [Praqma/helmsman#168]
We keep the certs for our tiller install in a separate location. Helmsman supports this for us by allowing us to specify the cert locations in the config for the namespace. Helmsman copies the required certs to the working directory where we are running Helmsman from.

My question is what is the desired state when Helmsman is finished running? We would prefer that those files it copied and/or created be deleted afterwards. It seems to leave the files around and now we have cert files copied around.

**Comment by sami-alajrami** [comment]
It is supposed to clean all certs after execution. This might be a bug, I will look into it.

**Comment by sami-alajrami** [comment]
@regner can you share the tail of the execution logs and what are the copied cert file names in the working directory? they are supposed to look like `<namespace>-tiller.cert <namespace>-tiller.key <namespace>-ca.cert `

**Comment by regner** [comment]
How much of the log did you want and did you want debug enabled?

The last two lines from our most recent run are:

```
2019/01/11 17:00:01 INFO: applying Helmsman labels to [ app-name ] in namespace [ some-namespace ]
2019/01/11 17:00:01 INFO: completed successfully!
```

Here are the files that are created:
```
kube-system-ca.cert
kube-system-client.cert
kube-system-client.key
kube-system-tiller.cert
kube-system-tiller.key
```

**Comment by sami-alajrami** [comment]
it is supposed to log some certs cleaning lines before it says `completed successfully` .. does the logs indicate that it is creating a new kube context? with something like:
```
INFO: KubeContext:   <context>  does not exist. I will try to create it.
```
It will only delete certs if it creates the kube context (because this is when it will download/copy them to local directory). 
Also which helmsman version are you using ?

**Comment by sami-alajrami** [comment]
if the kubeContext `staging-context-name` already exists, helmsman just uses it without copying any certs (and thus does not perform cleaning at the end). If the context does not exist, it will be created and this involves copying/downloading certs to the working directory and then deleting them upon successful completion. 
It is possible that these certs were left after a failed execution of helmsman where it terminated unexpectedly before cleaning the certs. You can verify by manually deleting them and going through a successful run of helmsman which should clean the certs.

**Comment by regner** [comment]
I have done that a few times. It still leaves the certs.

I am confused as to what these have to do with a context when they are certs for connecting to Tiller and where it would be downloading them from. It copies them from the defined location.

```
namespaces:
  kube-system:
    protected: false
    installTiller: true
    tillerServiceAccount: "tiller"
    caCert: "certslocation/ca.cert.pem"
    tillerCert: "certslocation/tiller.cert.pem"
    tillerKey: "certslocation/tiller.key.pem"
    clientCert: "certslocation/helm.cert.pem"
    clientKey: "certslocation/helm.key.pem"
```
