### ISSUE TITLE
Contradicting docs for `installTiller` effects

### ISSUE THREAD

**Issue by flypenguin** [Praqma/helmsman#170]
In [this example](https://github.com/Praqma/helmsman/blob/master/docs/how_to/multitenant_clusters_guide.md#deploying-tiller-with-tls-enabled) it says:

```toml
[namespaces]
    [namespaces.kube-system]
    installTiller = false # has no effect. Tiller is always deployed in kube-system
```
... whereas [here](https://github.com/Praqma/helmsman/blob/master/docs/how_to/define_namespaces.md#preventing-tiller-deployment-in-kube-system) it says:

> By default Tiller will be deployed into kube-system even if you don't define kube-system in the namespaces section. To prevent this, simply add kube-system into your namespaces section. Since installTiller for namespaces is by default false, Helmsman will not deploy Tiller in kube-system

combined with this code example, directly below:

```toml
[namespaces]
    [namespaces.kube-system]
    # installTiller = false  # this line is not needed since the default is false, but can be added for human readability.
```
If both are correct then please rewrite this so I can understand how one is not the complete opposite of the other :)
