### ISSUE TITLE
Using preinstalled Tiller with TLS still requires to specify tillerCert and tillerCert 

### ISSUE THREAD

**Issue by medzin** [Praqma/helmsman#185]
Using preinstalled Tiller with TLS still requires to specify `tillerCert` and `tillerCert` even though these values have no meaning in this context. 

```toml
[namespaces]
  [namespaces.kube-system]
    useTiller  = true
    tillerCert = "${HELM_HOME}/cert.pem" # need to specify something
    tillerKey  = "${HELM_HOME}/key.pem"  # need to specify something
    caCert     = "${HELM_HOME}/ca.pem"
    clientCert = "${HELM_HOME}/cert.pem"
    clientKey  = "${HELM_HOME}/key.pem"
```

Without providing these values, I get the "transport is closing" error.
