### ISSUE TITLE
Tiller cannot create Roles or RoleBindings if not running in kube-system namespace

### ISSUE THREAD

**Issue by flyhard** [Praqma/helmsman#186]
I have a RoleBinding in my application, and Tiller cannot create it if it runs in the same namespace. I needed to fix the privileges:

Before:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helmsman-tiller
  namespace: dev
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - '*'
    verbs:
      - '*'
```

after:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helmsman-tiller
  namespace: dev
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - rbac.authorization.k8s.io
    resources:
      - '*'
    verbs:
      - '*'

```

It feels like we could benefit from allowing a custom yaml file to be applied between the tiller creation and and the rest of the run.

_Originally posted by @flyhard in https://github.com/Praqma/helmsman/issues/125#issuecomment-461082911_
