### ISSUE TITLE
mapping the current helm state succeeds in osx and fails in jenkins

### ISSUE THREAD

**Issue by jpke** [Praqma/helmsman#188]
In osx 10.14, I run:
```
# version: v1.5.0

# metadata -- add as many key/value pairs as you want
metadata:
  org: '<org.com>'
  maintainer: 'Org (me@example.com)'
  description: 'Desired State File for CXD apps in k8s.'

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
certificates:

settings:
  kubeContext: '$CLUSTER_TARGETED'
  serviceAccount: 'tiller' # k8s serviceaccount. If it does not exist, it will be created.
  storageBackend: 'secret' # default is configMap
  # slackWebhook: "$slack" # or "your slack webhook url"
#  reverseDelete: false # reverse the priorities on delete

# define your environments and their k8s namespaces
# protected: <true or false> -- default to false
namespaces:
  kube-system:
    protected: false
    installTiller: true

# only private repos hosted in s3 buckets are now supported
helmRepos:
  stable: 'https://kubernetes-charts.storage.googleapis.com'

# define the desired state of your applications helm charts
apps:
  kube2iam:
    namespace: 'kube-system'
    enabled: true
    chart: 'stable/kube2iam'
    version: '0.9.1'
    name: 'kube2iam' # should be unique across all apps which are managed by the same Tiller
    valuesFile: '../cluster/kube2iam-config.yaml'
    purge: true
    test: false
    protected: false
    wait: true
    priority: -1
    # See https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps for more apps options
```
It returns 
``` _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.3
A Helm-Charts-as-Code tool.


2019/02/07 12:05:57 INFO: Parsed YAML [[ ./state/development.yaml ]] successfully and found [ 1 ] apps.
2019/02/07 12:05:57 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ kube-system ].
2019/02/07 12:05:58 WARN: I could not create namespace [ kube-system ]. It already exists. I am skipping this.
2019/02/07 12:05:58 INFO: deploying Tiller in namespace [ kube-system ].
2019/02/07 12:06:11 INFO: checking what I need to do for your charts ...
2019/02/07 12:06:11 INFO: mapping the current helm state ...
2019/02/07 12:06:17 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2019/02/07 12:06:17 INFO: Plan generated at: Thu Feb  7 2019 17:06:11
DECISION: release [ kube2iam ] is desired to be enabled and is currently enabled. Nothing to do here! -- priority: -1
2019/02/07 12:06:17 INFO: sorting the commands in the plan based on priorities (order flags) ...
2019/02/07 12:06:17 INFO: Nothing to execute ...
2019/02/07 12:06:17 INFO: completed successfully!
```

But, when I run the same block in Jenkins 2.150.1, I get:
```
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.7.3
A Helm-Charts-as-Code tool.


2019/02/07 17:09:06 INFO: Parsed YAML [[ ./state/development.yaml ]] successfully and found [ 1 ] apps.
2019/02/07 17:09:06 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ kube-system ]. 
2019/02/07 17:09:06 WARN: I could not create namespace [ kube-system ]. It already exists. I am skipping this.
2019/02/07 17:09:06 INFO: deploying Tiller in namespace [ kube-system ].
2019/02/07 17:09:09 INFO: checking what I need to do for your charts ... 
2019/02/07 17:09:09 INFO: mapping the current helm state ...
2019/02/07 17:09:10 [1;31mCommand returned with exit code: . And error message: Error: This command needs 2 arguments: release name, chart path
Usage:
  diff upgrade [flags] [RELEASE] [CHART]

Examples:
  helm diff upgrade my-release stable/postgresql --values values.yaml

Flags:
      --allow-unreleased         enables diffing of releases that are not yet deployed via Helm
  -C, --context int              output NUM lines of context around changes (default -1)
      --detailed-exitcode        return a non-zero exit code when there are changes
      --devel                    use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored.
  -h, --help                     help for upgrade
      --home string              location of your Helm config. Overrides $HELM_HOME (default "/var/lib/jenkins/.helm")
      --namespace string         namespace to assume the release to be installed into (default "default")
      --reset-values             reset the values to the ones built into the chart and merge in any new values
      --reuse-values             reuse the last release's values and merge in any new values
      --set stringArray          set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --set-file stringArray     set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
      --set-string stringArray   set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --suppress stringArray     allows suppression of the values listed in the diff output
  -q, --suppress-secrets         suppress secrets in the output
      --tls                      enable TLS for request
      --tls-ca-cert string       path to TLS CA certificate file (default "$HELM_HOME/ca.pem")
      --tls-cert string          path to TLS certificate file (default "$HELM_HOME/cert.pem")
      --tls-key string           path to TLS key file (default "$HELM_HOME/key.pem")
      --tls-verify               enable TLS for request and verify remote
  -f, --values valueFiles        specify values in a YAML file (can specify multiple) (default [])
      --version string           specify the exact chart version to use. If this is not specified, the latest version is used

Global Flags:
      --no-color   remove colors from the output

Error: plugin "diff" exited with error
```

Helm version on both:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
Helm plugin list on both:
```
NAME	VERSION 	DESCRIPTION
diff	2.11.0+2	Preview helm upgrade changes as a diff
s3  	0.7.0   	Provides AWS S3 protocol support.
    	        	h...
```

Any ideas?
