### ISSUE TITLE
helmRepos does not support username/password for adding repos with auth enabled

### ISSUE THREAD

**Issue by hasueki** [Praqma/helmsman#211]
Currently, Helmsman does not support adding of Helm repos that has authentication enabled. I don't see an option to do something like..

```
helm repo add --username <user> --password <pass> <helm-repo-url>
```

Ideally, the helmRepos block should support `username` and `password` parameters. 
```
...
helmRepos:
  some-repo:
    url: "https://helm-repo.url"
    username: $USER
    password: $PASS
...
```
Are there any plans to support something like this?
