### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by colachg** [Praqma/helmsman#219]
```
goroutine 1 [running]:
main.getReleaseChartName(0x4b, 0x0, 0xed426f60e, 0x0, 0xc000375550, 0x8, 0xc000452640, 0x18, 0xc000375558, 0x2, ...)
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/helm_helpers.go:188 +0x127
main.inspectUpgradeScenario(0xc0003aa000, 0x4b, 0x0, 0xed426f60e, 0x0, 0xc000375550, 0x8, 0xc000452640, 0x18, 0xc000375558, ...)
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/decision_maker.go:189 +0x494
main.decide(0xc0003aa000, 0x1402660)
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/decision_maker.go:59 +0x2ee
main.makePlan(0x1402660, 0x1)
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/decision_maker.go:21 +0x137
main.main()
	/Users/samialajrami/Praqma/projects/Go-projects/src/Helmsman/main.go:100 +0x2c2
```
Here is the output of `helm ls`:
```
NAME     	REVISION	UPDATED                 	STATUS  	CHART                   	APP VERSION	NAMESPACE
wx-server	75      	Fri Mar 22 15:28:14 2019	DEPLOYED	wx-server-38139-f17ebec3	           	wx       
```

**Comment by colachg** [comment]
helmsman version: v1.8.1

**Comment by hatemosphere** [comment]
@colachg could you please at least share your helmsman manifest?

**Comment by colachg** [comment]
```
apps:
  wx-server:
    chart: xxxxx/wx-server
    enabled: true
    namespace: wx
    purge: true
    version: 38512-72e6585e
helmRepos:
  xxx: http://example.com
namespaces:
  kube-system:
    installTiller: true
  wx: {}
settings:
  kubeContext: stage
```
@hatemosphere
