### ISSUE TITLE
How to improve run time on larger desired state files?

### ISSUE THREAD

**Issue by bgeesaman** [Praqma/helmsman#22]
First, thank you for sharing `helmsman` with the community.  When I kicked the tires on it using a smallish toml configuration with 2 apps, performance of a full run took a handful of seconds.  Everything was good.  But now, with ~30 helm charts defined and installed in a 10-node cluster, a CI run takes well over 8 minutes.  For bumping, say, a container version in a `values.yaml` for one app, this greatly slows iteration speed.  It appears to be ever-growing problem with regard to how many calls to `helm` there are and the increased time each `helm` call takes.  The logs show quite a few `helm` calls per chart, and each one takes 4 seconds to return.

```
$ time helm ls
...snip...
30 helm charts installed
...snip...
real	0m3.897s
user	0m0.173s
sys	0m0.070s
```

Also, with so many long runs, there is now a much higher likelihood of a race condition between multiple overlapping CI runs even 2+ minutes apart.  `helmsman` seems to gather its state in the beginning and then implement the work, so the second CI job will notice a chart is not there and then later go to implement it, only to error out because the first CI run placed it there in the meantime.

Any ideas/strategies for improving overall performance of each run?  I'd love to see things get under a minute, if possible.  Thanks!

**Comment by bgeesaman** [comment]
@sami-alajrami Thanks for that.  It's pretty much what I was thinking, too.  Reducing the number of calls to helm where possible is great, but the real pain is how long helm takes to run each command.  If I was to break up my deploys, say, per namespace, so that I'd have 5-6 apps instead of 30, it'd be a good bit faster, but I think I'd still have 4+ second calls to helm because of a shared Tiller deployment.  What about supporting the ```--tiller-namespace``` helm option through a TOML setting?  That way, I could break things out by namespace and have each tiller only handling/looking up what's in that namespace?

**Comment by sami-alajrami** [comment]
That's a good idea @bgeesaman .. how does the format below sound?  

```
 [settings]
kubeContext = "minikube"
installSharedTiller = false #  default is true
...
[namespaces]
  [namespaces.staging]
  protected = false
  installTiller= true
  [namespaces.production]
  protected = true 
  installTiller= false # default is false
... 
``` 
Then, when running helm commands, it implicitly either use the shared Tiller (if the desired namespace does not have its own), or use the specific Tiller of the namespace  (using `--tiller-namespace`)

**Comment by bgeesaman** [comment]
I was thinking it would be an `[apps.appname]` level configuration item like:

```toml
[apps]

    [apps.jenkins]
    name = "jenkins" # should be unique across all apps
    description = "jenkins"
    namespace = "staging" # maps to the namespace as defined in environments above
    tillerNamespace = "staging"
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/jenkins" # changing the chart name means delete and recreate this chart
    version = "0.14.3" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    protected = true
    # [apps.jenkins.set] # values to override values from values.yaml with values from env vars-- useful for passing secrets to charts
    #     db_username="$DB_USERNAME"
    #     db_password="$DB_PASSWORD"
    priority= -3
    wait = true

[apps]

    [apps.nginx]
    name = "nginx" # should be unique across all apps
    description = "nginx"
    namespace = "staging" # maps to the namespace as defined in environments above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/jenkins" # changing the chart name means delete and recreate this chart
    version = "0.14.3" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    protected = true
    # [apps.jenkins.set] # values to override values from values.yaml with values from env vars-- useful for passing secrets to charts
    #     db_username="$DB_USERNAME"
    #     db_password="$DB_PASSWORD"
    priority= -3
    wait = true
```

Where the `jenkins` is sent to the tiller in `staging` and the `nginx` is sent to the tiller in `kube-system`.  But I might be not fully aware of the architectural needs to say if that's doable.

**Comment by bgeesaman** [comment]
Also, I'm curious to know what it would take to be able to provide the TLS configuration items to be able to communicate securely.  Thanks!

**Comment by bgeesaman** [comment]
That seems reasonable as it would skip over an already deployed tiller in that namespace and not re-init it unnecessarily.

I deploy `tiller` via my cluster provisioning process and then trigger the CI pipeline with `helmsman` in it.  I have one `tiller` now, but as mentioned above, I'd like to break those out and add TLS configurations to each.  Since I will probably want to configure the `tiller` TLS settings differently per namespace (separating along team/project/CI pipeline needs), as long as I can specify those extra options somehow, that should work well!

**Comment by sami-alajrami** [comment]
@bgeesaman could you please try `v1.2.0-rc`  with a desired state similar to:

``` toml
[settings]
  # other options
serviceAccount = "foo" # the service account used to deploy tiller into namespaces if it does not have a specific one defined. If this one is not defined, the namespace default service account is used 
storageBackend = "secret" # default is configMap

[namespaces]
  [namespaces.production]
  protected = true
  installTiller = true # the foo service account above is used
  [namespaces.staging]
   protected = false
   installTiller = true
   tillerServiceAccount = "tiller-staging" # should already exist in the staging namespace
   caCert = "secrets/ca.cert.pem" # or an env var, e.g. "$CA_CERT_PATH" 
   tillerCert = "secrets/tiller.cert.pem" # or S3 bucket s3://mybucket/tiller.crt
   tillerKey = "secrets/tiller.key.pem"  # or GCS bucket gs://mybucket/tiller.key
   clientCert = "secrets/helm.cert.pem"
   clientKey = "secrets/helm.key.pem"

[apps]

    # jenkins will be deployed using the Tiller deployed in the staging namespace
    # if the staging namespace wasn't configured to deploy Tiller, the kube-system Tiller will be used
    # Tiller will always be deployed into kube-system regardless of defining it in the namespaces section or not. You can ,however, configure it to use a specific service account and TLS  
    [apps.jenkins]
    name = "jenkins" 
    description = "jenkins"
    namespace = "staging" 
    enabled = true 
    chart = "stable/jenkins" 
    version = "0.14.3" 
    valuesFile = "" 

```
> There is no `tillerNamespace` flag supported for apps. This proved to introduce some complexities if a user change it (will leave multiple deployments of the same release managed by different Tillers).

Regarding performance:

- The new release replaces many helm calls with a single one for building the current state.
- Using multiple Tillers introduces some latency due to deploying Tillers and waiting for them to be ready. 
- You can use `--skip-validation` if you are confident that your desired state is valid. This can save you some ~10 seconds or so.
- Avoid using the wait flag unless necessary.
- Use the protected flag to skip unnecessary upgrades for apps that are meant to change.

It would be great if you could test this release in your context and let me know how the performance improves when using multiple Tillers. Thanks!
