### ISSUE TITLE
Feature - Helm Dependency Update

### ISSUE THREAD

**Issue by eperdeme** [Praqma/helmsman#231]
Hello,

I'm trying to extend a chart by having a local chart to add a few extra Kubernetes settings (istio config).

The local chart has a requirements.yaml file which specifies the upstream chart dependency. 
During a chart run I can do;
helm dep update
helm install/upgrade ./mychart

However in helmsman I can not find a way to make it do a dep update prior to attempting to install the chart.

helmsman.yaml
```
  dashboard:
    namespace: kube-system
    enabled: true
    chart: ../charts/kube-dashboard
    version: 0.1.0
```

Chart requirements file
```
dependencies:
  - name: kubernetes-dashboard
    version: 1.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
```

error
```
2019/04/16 11:46:48 Command returned with exit code: . And error message: Error: found in requirements.yaml, but missing in charts/ directory: kubernetes-dashboard
```
