### ISSUE TITLE
Feature Request: special ignored keys in yaml for using anchors in configuration

### ISSUE THREAD

**Issue by mkjmdski** [Praqma/helmsman#300]
Hey!
I think this would be pretty simple to implement, so basically I would like to have a key in my yaml configuration which would look like that

```yaml
.service: &service-template
  enabled: true
  valuesFiles:
    - "../values/dev.yaml"
  secretsFiles:
    - "../values/dev.secrets.yaml"
  wait: true
  purge: true
```
so any key starting in yaml with . would be ignored, so later on I could write something like this

```yaml
  prometheus:
    <<: *service-template
    namespace: "prometheus"
    chart: "prometheus"
    version: "1.0.0"
    name: "prometheus"
    priority: -998
```

currently this configuration is producing error that `.service` is not  known. This would be very helpful in writing DRY configs in yaml for helmsman
