### ISSUE TITLE
Regression: cannot upgrade Job.Batch

### ISSUE THREAD

**Issue by lhotrifork** [Praqma/helmsman#308]
Hey,

I have an issue using version v1.12.0 of helmsman where I get a validation error with an invalid template. It used to work in v.1.10.1.

```
Command returned with exit code: . And error message: Error: UPGRADE FAILED: Job.batch "myapplication" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"release":"myapplication", "app.kubernetes.io/name":"myapplication", "job-name":"myapplication", "controller-uid":"76a66697-f003-11e9-8186-02649c020e76", "heritage":"Tiller", "helm.sh/chart":"management-job-0.9.0", "version":"required", "app":"myapplication", "chart":"management-job-0.9.0", "app.kubernetes.io/managed-by":"Tiller", "app.kubernetes.io/component":"myapplication-myapplication", "app.kubernetes.io/version":"required", "component":"myapplication-myapplication", "app.kubernetes.io/instance":"myapplication"}, Annotations:map[string]string{"checksum/config":"0a7e3ecbf2580ef24e5048df411e6a64d9bc7c19cf8f3a188faccaa46dbe0479", "sidecar.istio.io/inject":"false", "vault.security.banzaicloud.io/vault-addr":"https://vault:8200", "vault.security.banzaicloud.io/vault-env-passthrough":"VAULT_ADDR,VAULT_ROLE", "vault.security.banzaicloud.io/vault-role":"myapplication-myapplication"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:"config-volume", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(0xc0298602c0), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"myapplication", Image:"myregistry.domain.com/myapplication:master-721e854", Command:[]string(nil), Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"VAULT_TOKEN", Value:"vault:login", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:100, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"100m", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:134217728, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}}, Requests:core.ResourceList{"cpu":resource.Quantity{i:resource.int64Amount{value:100, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"100m", Format:"DecimalSI"}, "memory":resource.Quantity{i:resource.int64Amount{value:67108864, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"BinarySI"}}}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:"config-volume", ReadOnly:false, MountPath:"/data/users.yaml", SubPath:"users.yaml", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*core.SecurityContext)(0xc002e82000), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc025481658), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"myapplication", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc026de3f80), ImagePullSecrets:[]core.LocalObjectReference{core.LocalObjectReference{Name:"harbor"}}, Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}: field is immutable
```
I'm not actually updating the job itself, but rather a configmap used by the job.

```yaml
myapplication, myapplication-configmap, ConfigMap (v1) has changed:
  # Source: management-job/templates/configmap.yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: myapplication-configmap
    labels:
      app: "myapplication"
      chart: "management-job-0.9.0"
      component: "myapplication-myapplication"
      heritage: "Tiller"
      release: "myapplication"
      version: "required"
      app.kubernetes.io/name: myapplication
      helm.sh/chart: "management-job-0.9.0"
      app.kubernetes.io/managed-by: "Tiller"
      app.kubernetes.io/instance: "myapplication"
      app.kubernetes.io/version: "required"
      app.kubernetes.io/component: "myapplication-myapplication"
  data:
    users.yaml: |-
      users:
        - application: appname1
          name: data

        - application: appname1
          name: otherdata

        - application: appname2
          name: otherdata

        - application: appname3
          name: otherdata

        - application: appname4
          name: otherdata

        - application: appname5
          name: otherdata

        - application: appname6
          name: otherdata

        - application: appname7
          name: otherdata

        - application: appname8
          name: otherdata
+
+       - application: appname9
+         name: otherdata
myapplication, myapplication, Job (batch) has changed:
  # Source: management-job/templates/job.yaml
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: myapplication
    labels:
      app: "myapplication"
      chart: "management-job-0.9.0"
      component: "myapplication-myapplication"
      heritage: "Tiller"
      release: "myapplication"
      version: "required"
      app.kubernetes.io/name: myapplication
      helm.sh/chart: "management-job-0.9.0"
      app.kubernetes.io/managed-by: "Tiller"
      app.kubernetes.io/instance: "myapplication"
      app.kubernetes.io/version: "required"
      app.kubernetes.io/component: "myapplication-myapplication"
    annotations:
-     checksum/config: b2ce327cb0d4df1a9583862f53dd888c8ae5909c367157811c4361c19005a401
+     checksum/config: 0a7e3ecbf2580ef24e5048df411e6a64d9bc7c19cf8f3a188faccaa46dbe0479
  spec:
    backoffLimit: 0
    template:
      metadata:
        labels:
          app: "myapplication"
          chart: "management-job-0.9.0"
          component: "myapplication-myapplication"
          heritage: "Tiller"
          release: "myapplication"
          version: "required"
          app.kubernetes.io/name: myapplication
          helm.sh/chart: "management-job-0.9.0"
          app.kubernetes.io/managed-by: "Tiller"
          app.kubernetes.io/instance: "myapplication"
          app.kubernetes.io/version: "required"
          app.kubernetes.io/component: "myapplication-myapplication"
        annotations:
          vault.security.banzaicloud.io/vault-addr: https://vault:8200
          vault.security.banzaicloud.io/vault-role: myapplication-myapplication
          vault.security.banzaicloud.io/vault-env-passthrough: "VAULT_ADDR,VAULT_ROLE"
          sidecar.istio.io/inject: "false"
-         checksum/config: b2ce327cb0d4df1a9583862f53dd888c8ae5909c367157811c4361c19005a401
+         checksum/config: 0a7e3ecbf2580ef24e5048df411e6a64d9bc7c19cf8f3a188faccaa46dbe0479
      spec:
        serviceAccountName: myapplication
        restartPolicy: Never
        imagePullSecrets:
          - name: harbor
        volumes:
          - name: config-volume
            configMap:
              name: myapplication-configmap
              items:
              - key: users.yaml
                path: users.yaml
        containers:
          - name: myapplication
            securityContext:
              runAsNonRoot: false
            image: "myregistry.domain.com/myapplication:master-721e854"
            imagePullPolicy: "Always"
            volumeMounts:
                - name: config-volume
                  mountPath: /data/users.yaml
                  subPath: users.yaml
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "100m"
                memory: "128Mi"
            env:
            - name: VAULT_TOKEN
              value: "vault:login"
```
