### ISSUE TITLE
Local charts not working

### ISSUE THREAD

**Issue by kpucynski** [Praqma/helmsman#310]
Local charts were working fine on helmsman up to `1.11.0`, defined by specifying local path:
```
  ingress:
    enabled: true
    chart: "./charts/nginx-ingress"
    version: "1.3.1"
```
The same config is not working on `1.12.0`:
```
18:14:28  2019/10/21 16:14:28 ERROR: chart /home/jenkins-slave/workspace/xxx/charts/nginx-ingress-1.3.1 is specified for but version is not found in the defined repo.
```
No files were moved in the repository. Files on host are existing.
Reverting to version `1.11.0` fixes the issue.
