### ISSUE TITLE
Add possibility to install chart using tiller from different namespace

### ISSUE THREAD

**Issue by krogon** [Praqma/helmsman#32]
This is useful if there is more granularity of namespaces.

Example:
Namespaces: 
```
production-frontend
production-backend
production-tools

staging-frontend
staging-backend
staging-tools
...
```
Tiller is only installed in `production-tools` or equivalent environment: `staging-tools`, `testing-tools`, etc..

**Comment by sami-alajrami** [comment]
we could add a `tillerNamespace` flag for this with each app like : 

```toml
[apps.jenkins]
    name = "jenkins" 
    description = "jenkins"
    namespace = "staging" 
    tillerNamespace = "MY_PREFERED_TILLER"
    enabled = true 
    chart = "stable/jenkins" 
    version = "0.14.3" 
    valuesFile = "" 
```

when installing for the first time, this is straightforward .. but if later you change the `tillerNamespace` to some other namespace, then what happens?

a) delete from the previous Tiller and install from scratch with the new Tiller ? 
b) keep multiple copies of the release (with the same name) managed by two (or more) Tillers?

I think the two options have some side effects:
problem with option a): you lose the history of your release 
problem with option b): it might become confusing (and wasteful) to have multiple copies  of the release and Helmsman has to cope with that to update and maintain the right one only.

@krogon what are your thoughts on this?
