### ISSUE TITLE
Support `--set-file` flag

### ISSUE THREAD

**Issue by sc250024** [Praqma/helmsman#332]
# Description

Helmsman has support for the flag `--set` and `--set-string` as `set` and `setString` respectively. It should support the `--set-file` flag as `setFile` as well.

**Comment by sami-alajrami** [comment]
@sc250024 have you tried to add setFile with the existing `helmFlags` option?
should look like this (haven't tested it though):
```yaml
app: 
    example:
        ...
        helmFlags: 
            - "set-file key1=path1,key2=path2"
```
The `helmFlags` option allows to pass any additional helm flags for a specific release.
