### ISSUE TITLE
multiline text block within the `set` block

### ISSUE THREAD

**Issue by Azulinho** [Praqma/helmsman#351]
Having trouble passing a multiline block of text to my `set` dictionary,
I've noticed that the YAML implementation within the `set` block is a bit funky and doesn't really follow the YAML spec

```
2019/12/27 17:33:11 INFO: substituting env variables in file:  /workdir/stacks/graylog.config.yaml
2019/12/27 17:33:11 INFO: substituting SSM variables in file:  /workdir/stacks/graylog.config.yaml
2019/12/27 17:33:11 yaml: unmarshal errors:
  line 162: cannot unmarshal !!map into string
  line 166: cannot unmarshal !!map into string
```

```
 graylog_logstash:
    namespace: "graylog"
    tillerNamespace: "graylog"
    enabled: true
    purge: false
    version: 7.5.1
    chart: "elastic/logstash"
    name: "graylog-logstash"
    description: "logstash"
    helmFlags: [ "--timeout=600" ]
    test: false
    protected: false
    wait: false
    set:
      ingress.enabled: true
      ingress.hosts[0]: "logstash.kubernetes.stuff"
      persistence.enabled: true
      volumeClaimTemplate.storageClassName: "nfs-client"
      volumeClaimTemplate.accessModes[0]: "ReadWriteMany"
      volumeClaimTemplate.resources.requests.storage: "1Gi"
      rbac.create: false
      updateStrategy: "OnDelete"
      maxUnavailable: false
      logstashConfig:
        logstash.yml: |-
          http.host: 0.0.0.0
          xpack.monitoring.enabled: false
      logstashPipeline:
        uptime.conf: |-
          input { exec { command => "uptime" interval => 30 } }
          output { elasticsearch { hosts => ["http://graylog-elasticsearch-client.graylog:9200"] index => "logstash" } }
```

It looks that it doesn't support the multiline YAML indicator `|-`, I tried a few of the different variations but it doesn't seem to be soaking the YAML as yaml.

is there a way to pass a multiline block of text? without using many `\n` in a single line?

**Comment by sami-alajrami** [comment]
since you have several values being set, why not have your custom values file instead?
Also, which version of Helmsman are you using?

**Comment by Azulinho** [comment]
Hi @sami-alajrami 
I am work-around-it by using a values.yaml, however I would prefer to keep everything in one file.
I currently have one state.yaml file per namespace, and dedicated tillers on each namespace.

Had a look into the go library used and it looks to support the pipe operator, not sure why this wasn't eating it

**Comment by Azulinho** [comment]
v1.13.0 btw

**Comment by anouarchattouna** [comment]
Hello, same error reproduced using:
* helmsman **v3.3.0**
* helm **v3.2.0**

BTW, I used the example provided from the [desired_state_specification](https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#apps) documentation
```yaml
apps:
  jenkins:
    name: "jenkins"
    description: "jenkins"
    namespace: "staging"
    enabled: true
    group: "critical"
    chart: "stable/jenkins"
    version: "0.9.0"
    valuesFile: ""
    test: true
    protected: false
    wait: true
    priority: -3
    helmFlags: [
      "--recreate-pods",
    ]
    set:
      secret1: "$SECRET_ENV_VAR1"
      secret2: "$SECRET_ENV_VAR2"
    setString:
      longInt: "1234567890"
      image:
        tag: "1.0.0"
```
```log
2020-04-30 17:16:28 CRITICAL: yaml: unmarshal errors:
  line 52: cannot unmarshal !!map into string
```

**Comment by sami-alajrami** [comment]
Hi @Azulinho @anouarchattouna and apologies for the late reply.
`set`, `setString` and `setFile` are defined as map[string]string. This means they can't process nested elements. Instead you can group your nested elements in one line (like you would do on helm's CLI). e.g 
```yaml
...
set:
   "controller.image.tag": "v1.0.0"
```
```toml
...
set:
   "controller.image.tag"= "v1.0.0"
```
I have updated the docs and fixed the wrong example.
