### ISSUE TITLE
Feature suggestion: have the ability to add pre and post deploy actions

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/helmsman#360]
The idea I have is to allow referencing k8s yaml manifests to be applied before or after operating on a release in the DSF. 

This is useful in scenarios where you need to deploy something that's not part of a 3rd party helm chart. For example, install CRDs (if they are not packaged in the chart), create a secret or a configmap needed by the chart, or perform some post-installation processing.

Some of these cases can be implemented by helm lifecycle hooks if you manage the chart. But with 3rd party charts, you don't always get these.

The format could be something like this:
```yaml
...
nexus:
      pre-install: create-my-nexus-password-secret.yaml
      namespace: utils
      enabled: true
      chart: "stable/sonatype-nexus"
      valuesFile: "values-files/nexus-values.yaml"
      version: "1.21.3"
      priority: -5
```

Upon installation/upgrade of this release, we can do `kubectl apply` and upon deletion, we do `kubectl delete`. 
I would not want to allow arbitrary scripts for these hooks, because we can't control their effect (example we can't easily reverse the effect of a script if the release is deleted).
If this feature is desired, I can have a go at implementing it.

**Comment by galindro** [comment]
@sami-alajrami are you working on this feature?

**Comment by sami-alajrami** [comment]
@galindro no, I haven't started working on this yet.

**Comment by PirateBread** [comment]
Many charts require pre-reqs, as mentioned, CRDs for example. This would be an excellent feature.

**Comment by kferrone** [comment]
I would personally like to include prereqs with kustomize in helm chart so all resources are managed together. In issue #414 I show how to use helmflags and `--post-renderer` to use kustomize to add whatever you like to the release and Helm now will statefully include those resources in the release. If it is just a pre-install post-install hook, then helmsman would have to manually manage these resources outside of helm. 

The original request in #414 suggests supporting kustomize as a Helmsman feature, I feel this would satisfy the pre-post install hooks much better. All the fancy plugins and features of kustomize would be available, you can generate and inject secrets into a chart too. I was even able to inject jobs with [helm-hooks](https://helm.sh/docs/topics/charts_hooks/) on them into charts I don't manage. Then helm can manage it all like helm do. 

With the helm [`--post-renderer`](https://helm.sh/docs/topics/advanced/) flag it just wants an executable. If Helmsman provided that executable then it could be what handles kustomize and one could simply point to a kustomization.yaml. Then ya'll could add a `postRenderer` option to the app to provide some custom renderer after the kustomization runs which is run by the built in helmsman post renderer. 

```yaml
nexus:
      namespace: utils
      enabled: true
      chart: "stable/sonatype-nexus"
      valuesFile: "values-files/nexus/values.yaml"
      kustomization: "values-files/nexus/kustomization.yaml"
      version: "1.21.3"
      priority: -5
      postRenderer: ./hello.sh
```
kustomization.yaml
```yaml
commonLables:
   somelabel: foo-bar
resources:
- all.yaml # this is here because it is the rendered k8s resource from helm when run as post render
- create-my-nexus-password-secret.yaml
- helm-pre-install-job.yaml
```

`./hello.sh`
```bash
echo "hello helmsman"
# and just because you can do whatever in postRender
kubectl apply -f values-files/nexus/unmanaged-pre-install-resource.yaml
```

Ultimately this way the Helmsman team would have less code to write and kustomize would do all the heavy lifting. I also vote against putting kustomize in a black-box, i.e. I would rather have full control over kustomization just Like I do my own charts. It would be weird if ya'll tried to integrate the kustomization yaml straight into the helmsman/dsf file. 

Inspiration and Innovation!
