### ISSUE TITLE
question/feature: namespaceTemplates

### ISSUE THREAD

**Issue by galindro** [Praqma/helmsman#388]
Would be nice if helmsman could provide a namespaceTemplates alongside appsTemplates. This would avoid code repetition like this:

```yaml
namespaces:
  teleport:
    labels:
      monitoring: true
  gloo:
    labels:
      monitoring: true
    annotations:
      discovery.solo.io/function_discovery: enabled
  loki-stack:
    labels:
      monitoring: true
    annotations:
      discovery.solo.io/function_discovery: enabled
  prometheus-operator:
    labels:
      monitoring: true
    annotations:
      discovery.solo.io/function_discovery: enabled
```

With namespaceTemplates, it could be rewrite as:

```yaml
namespaceTemplates:
  label_defaults: &label_defaults
    labels:
      monitoring: true
  annotation_defaults: &annotation_defaults
    annotations:
      discovery.solo.io/function_discovery: enabled

namespaces:
  teleport:
    <<: *label_defaults
  gloo:
    <<: *label_defaults
    <<: *annotation_defaults
  loki-stack:
    <<: *label_defaults
    <<: *annotation_defaults
  prometheus-operator:
    <<: *label_defaults
    <<: *annotation_defaults
```
