### ISSUE TITLE
Error: Multiple versions of chart found in the helm repositories

### ISSUE THREAD

**Issue by boxcee** [Praqma/helmsman#396]
I get an error when having kubedb and kubedb-catalog charts in the desired state file. The error only appears on **second** run though. When I remove all installed charts and install from _scratch_, the deployment succeeds. A second run will throw this error message though:
```
CRITICAL: Multiple versions of chart [ appscode/kubedb ] with version [ 0.12.0 ] found in the helm repositories
```

Helmsman: `3.0.2`

DSF.yaml:
```
apps:
  kubedb:
    name: "kubedb"
    namespace: "kubedb"
    chart: "appscode/kubedb"
    version: "0.12.0"
    priority: -7
    enabled: true
  kubedb-catalog:
    name: "kubedb-catalog"
    namespace: "kubedb"
    chart: "appscode/kubedb-catalog"
    version: "0.12.0"
    priority: -7
    enabled: true
helmRepos:
  appscode: "https://charts.appscode.com/stable"
namespaces:
  kubedb:
    labels:
      role: "kubedb"
settings:
  kubeContext: $KUBECONTEXT
```

Command I run:
```
helmsman -f desired-state-file.yaml -subst-env-values --apply
```
