### ISSUE TITLE
Unexpected deletion of releases when namespace, but no releases are present in DSF

### ISSUE THREAD

**Issue by boxcee** [Praqma/helmsman#406]
Not sure whether this is expected or not, but it is a breaking change between version 2 and 3 at least.
Take this DSF:
```
apps:
  cert-manager:
    name: "cert-manager"
    namespace: "cert-manager"
    chart: "jetstack/cert-manager"
    version: "0.13.0"
    enabled: true
helmRepos:
  jetstack: "https://charts.jetstack.io"
namespaces:
  cert-manager:
    labels:
      role: "cert-manager"
```
Then, apply this DSF:
```
apps:
  chartmuseum:
    name: "chartmuseum"
    namespace: "chartmuseum"
    chart: "stable/chartmuseum"
    version: "2.7.1"
    enabled: true
helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
namespaces:
  cert-manager:
    labels:
      role: "cert-manager"
  chartmuseum:
    labels:
      role: "chartmuseum"
```
The application of the second DSF will now delete all releases in the `cert-manager` namespace.
