### ISSUE TITLE
Dry running creates namespace

### ISSUE THREAD

**Issue by sheerun** [Praqma/helmsman#424]
example.yaml:

```
namespaces:
  foobar:
    labels:
      env: foobar
```

command:

```
helmsman --debug --dry-run -f example.yaml
```

expected:

cluster is not changed

happened:

foobar namespace has been created
