### ISSUE TITLE
Using appsTemplate and set issues

### ISSUE THREAD

**Issue by mal-berbatovci** [Praqma/helmsman#435]
Hi, I'm using Helmsman 1.13.2 (My helm client is still not on v3, so I can't update to helmsman v3+), and I'm having difficulty using AppsTemplate and Set together. 

I have three different variables I want to substitute in my value files. Example:

```
server:
  global:
    scrape_interval: 30s
    external_labels:
      promserver: prom-${ENV}
```

And I have this defined as an DSF:
```
appsTemplates:
  default: &default
    set:
      ENV: "loadtest"

apps:
  loadtest-prometheus:
      <<: *default
      namespace: "monitoring"
      enabled: true
      chart: "stable/prometheus"
      version: "9.1.0"
      valuesFiles: [
        "../../global-values/prometheus/prometheus.yaml"
      ]
      protected: false
      wait: true
```

But when I do a `helmsman --show-diff -f ..` none of these variables are being substituted. I can see that Helmsman says it is `substituting env/SSM variables in file`, but all of them are left blank. Even when I remove the appsTemplate and just use set  in the apps definition, the same thing happens. I've tried to look at the code and other issues to understand what is happening, but my understanding is that in the K:V pair if the V doesn't exist as a env variable, then the value V is used. However, It only seems to work if I set those K:V as environment variables explicitly and do not use set

I've also  tried looking at the new appsTemplate examples but none of them are using set inside  an appsTemplate definition. 

Am I doing something wrong here or is this a limitation of  earlier versions of Helmsman / using  appsTemplate and Set together? Thanks
