### ISSUE TITLE
Feature Request: Configure helm revisions retained by helmsman

### ISSUE THREAD

**Issue by totallyzen** [Praqma/helmsman#443]
# Issue

- Helmsman allows lots of apps to be deployed in the same namespace.
- Helm 3 onwards it stores the specifics of the revision in K8s secrets
- Helm by default keeps the last 10 revisions of your release
- If you have hundreds of apps (we have almost 500 apps across 20 or so users) then multiply that by 10 -> you get an enormous number of secrets stored in the same namespace 
- This will slow down any operation involving Kubernetes secrets including helm/helmsman deployments

# Proposal

Helm already supports `--max-history <int>` on the `upgrade` operation. We should allow helmsman apps to expose this feature and let owners of the DSFs decide how many revisions to keep.

Example DSF:
```yaml
context: my user
metadata:
  generated_by: my_tool
namespaces:
  my-namespace: {}
preconfiguredHelmRepos:
- company-artifactory
apps:
  my-example-service:
    chart: company-artifactory/my-chart
    version: 0.4.0
    enabled: true
    max_history: 2  # only keep 2 revisions after upgrade
...
    valuesFiles:
    - ./_my_user_settings.yaml
    - ./service-value-file.yaml
...
    wait: true
  my-other-example-service:
...
    history: 1. # only keep the one revision
```

Note:
- use whatever casing makes most sense for `max_history` (e.g.: `maxHistory` instead) - no opinion on this one

**Comment by sami-alajrami** [comment]
have you tried using the helmFlags option? may not work with install commands though since the flag does not exist for install commands (AFAIK)

```yaml
apps:
  my-example-service:
    chart: company-artifactory/my-chart
    version: 0.4.0
    enabled: true
    helmFlag: 
       - "--history-max 2"
```
