### ISSUE TITLE
Sensible default values for settings

### ISSUE THREAD

**Issue by flypenguin** [Praqma/helmsman#45]
**Use this config:**

```yaml
apps:
  nginx-ingress-ext:
    description:  enable nginx ingress controller
    namespace:    kube-system
    chart:        stable/nginx-ingress
    version:      0.22.1
```

**Expected result:**

* That `stable/nginx-ingress` is deployed as `nginx-ingress-ext` in the namespace `kube-system`.

**Actual result:**

* an error is issued that the name is required (proposal: fallback to `nginx-ingress-ext` as parent key name, which is what I think most people would expect)
* if you add the name, it is not deployed (proposal: default to `enabled: true` which is IMO the more common scenario

**Comment by flypenguin** [comment]
actually ;) it's not about any wrong documentation / examples. It's about changing the defaults.
To me the "normal" use case is to install the chart, and the name could be taken from the parent key, which has otherwise absolutely no use and could also be an array (cause the value of the parent key is never used). that way you could remove boilerplate code - the above definition in my example is two lines shorter than right now, which is about 29%. even more if you remove the description.

**Comment by sami-alajrami** [comment]
@flypenguin I see your point. Will have a look to make this change with backward compatibility. Description is already optional ;)

**Comment by krogon** [comment]
@flypenguin the upper key is the unique identifier of the chart release. You can have multiple chart releases with the same name, as you can manage multiple tillers (`tillerNamespace` parameter).

I agree that identifier can be used as chart name by default, but `name` still have to exist.

**Comment by flypenguin** [comment]
I don't quite get it. do you say you still need the /possibility/ of the `name` field, or the /actual/ name field every time? with the 1st one I'd of course agree. But to deploy 2 ingresses I would like to do this:

```yaml
apps:
  ingress-1:
    chart: ...
    version: ...
    namespace: ...
    valueFile: ...
  ingress-2:
    # same here.
```

and to me that should be enough ... right?

**Comment by sami-alajrami** [comment]
@flypenguin what @krogon means is that if you use multiple Tillers in the same cluster, you can have releases with the same name as long as they are managed by different Tillers (in different namespaces). 

TOML (and possibly YAML also) does not allow having duplicate keys as in the following: 
```toml
[apps]
[apps.ingress-1]
...
[apps.ingress-1]
...
```
In this case, you need to use the name option:
```toml
[apps]
[apps.ingress-1]
name = "ingress-1"
...
[apps.ingress-2]
name = "ingress-1"
...
```
The example above of course assumes you have two Tillers in two namespaces and each of them is managing one of the `ingress-1` releases.

So what we need to have is make the `name` optional, if not defined the YAML or TOML key is used as a release name. And `name` is defined, it has higher precedence. This is to support all use cases and also to be backwards-compatible.

**Comment by krogon** [comment]
... and yaml example ...
```yaml
apps:
  jenkins-prod:
    name: jenkins
    tillerNamespace: prod
    ...
  jenkins-test:
    name: jenkins
    tillerNamespace: test
    ...
```

**Comment by flypenguin** [comment]
@sami-alajrami yup, we are fully on the same page here :) .

**Comment by sami-alajrami** [comment]
I was looking at this and realized that while using same release names with multiple Tillers (as in the examples above) is legal by helm, helmsman validation currently does not accept it as it checks for uniqueness across all Tillers/namespaces. I created a new issue #50 to fix this.

**Comment by krogon** [comment]
Saw that before, forgot to report :/

**Comment by sami-alajrami** [comment]
names are now optional in v1.4.0-rc, but the `enabled` option still defaults to false. 
This is the minimal config for an app:

TOML: 
```toml
[apps]
[apps.jenkins]
 namespace = "staging" 
 enabled = true 
 chart = "stable/jenkins" 
 version = "0.14.3"
```

or YAML:
```yaml
apps:
  jenkins:
    namespace: staging
    enabled: true
    chart: stable/jenkins
    version: 0.14.3
```
