### ISSUE TITLE
Bug: secretsFiles should enforce the namespace if not present

### ISSUE THREAD

**Issue by orefalo** [Praqma/helmsman#452]
When pointing to a secretFile yaml, and this one has no namespace defined.
helmsman should create the secret in the namespace defined by the app.release.

At this point, they are created in the default namespace.

ie.
```
apps:
  nginx-ingress:
    enabled: true
    namespace: "nginx-ingress"
    chart: "stable/nginx"
    version: "1.36.3"
    secretsFiles:
      - "./secrets/tls-ingress.yaml"


> kubectl get secrets # (default namespace)
NAME                                   TYPE                                  DATA   AGE
tls-snapcore-ingress                  kubernetes.io/tls                     2      3m4s
...
```

**Comment by mkubaczyk** [comment]
`secretsFiles` are the same things as valuesValues but they are just encrypted, so this basically is encrypted values file, not a kubernetes resource definition in yaml

**Comment by orefalo** [comment]
Hi,

secrets are typically used to fetch docker images in private repos. As such, they must be copied in multiple namespaces

Allowing the current processed namespace as the default namespace allows to create one file for all, rather than one file for each.

**Comment by mkubaczyk** [comment]
Ok, let's try it another way. Show us the content of:
"./secrets/tls-ingress.yaml"

**Comment by orefalo** [comment]
ENC[PKCS7,MIIDLQYJKoZIhvcNAQcDoIIDHjCCAxoCAQAxggEhMIIBHQ....js3EZF4g==]

**Comment by mkubaczyk** [comment]
At this point I might need to take a look at decrypted content of that file. Just remove any fragile parts of it.

**Comment by eperdeme** [comment]
Slightly related but more to show how we use secretfiles for another use case via helm-secrets;

helmsman.yaml
````apps:
  gitlab-runner:
    namespace: gitlab-runners
    enabled: true
    chart: ../charts/gitlab-runners
    version: 1.0.0
    valuesFiles:
      - "apps/gitlab-runner.yaml"
    secretsFiles:
      - "envs/${env}.yaml"
````

Then in env/dev.yaml or prod.yaml it contains the SOPS encryption

````
gitlab-runner:
    runnerRegistrationToken: ENC[AES256_GCM,data:Hz7ytHIzdw1gHLhQ66/eXo5JsXw=,iv:ExfR2+zZJkJ8mHJQ51Sur7W/QHxshllqcRqKM2aUJok=,tag:zGPS1/zIjGciQwW6szTI/g==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:eu-west-1:1234123:alias/applications
        created_at: '2020-05-07T13:37:28Z'
        enc: AQICAHj7JvQsllctqH8/kQXr77nO9R2YWjUPt2/iZpZKp4WglgGI5fWJQMB9cBT4M7F+nZuSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMi1n2zexI5PqOYK5BAgEQgDvr3eA9i7Gbev5dO/h+K8sbET0uktLWOhZ0U1t6AuzOxjXgJJU3tHAYA09zSE+jFTMxgiKbNwZ6Ku8nGA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-07T13:37:29Z'
    mac: ENC[AES256_GCM,data:FHvNuGlAjAS8bGk/gR+zy+fNUbMM/kDn3JgIyQfze57FJpxZl4hceVsgR1lx0YqQgzSJj+5eErhPSFBK7Xah4QPe7RcNFHBNypy0j+v6Y03+Vpw2PxGBoHTC+4+VQJ01tFXH4K1Hd4Jf+/r1aobNP3KXvNWZlEIIvfS115UOIVc=,iv:lvKG4NpP0a8oFJq/Xy8urvbBI8q7IO/XjkEwidkjy7w=,tag:eOQ84EBc77MuFumCyQ1reg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
````

We then run
````
helmsman -e envs/${environment}.env -f helmsman.yaml
        -update-deps --show-diff -no-ssm-subst  --subst-env-values
````

So not too sure how you're doing it but sounds interesting, but I don't see how secret files relate to NS as they just get decrypted and passed in to helm as variables, merged with valuesFiles.
