### ISSUE TITLE
Bug: 1st item of secretsFiles not processed

### ISSUE THREAD

**Issue by orefalo** [Praqma/helmsman#454]
When using multiple secret files, the first item is not processed.
   for/loop index issue I believe.

Will try to fix this one, although I am no GO developer.

``` 
 myapp:
    enabled: true
    test: false
    wait: false
    namespace: "default"
    chart: "somechart"
    secretsFiles:
      - "./secrets/secret1.yaml"
      - "./secrets/secret2.yaml"
    version: "1.0.0"
    valuesFile: "./charts/some_values.yaml"
```
