### ISSUE TITLE
Issue running helmsman on KOPS on top of AWS

### ISSUE THREAD

**Issue by iamaverrick** [Praqma/helmsman#474]
we are trying to use helmsman on our AWS account. we used KOPS to deploy a K8s cluster and currently we are trying to use helmsman to deploy all of our helm charts on the already running cluster. 

we tested our script on minikube environment and it works just fine while defining "minikube" as kubeContext. but when deploying it to the prod environment the script fails to deploy correctly with no error message. it just gets stuck for hours which i have to terminate the terminal and launch a new one.

Helsman Version - v3.4.1
Helm v3.2.1"
Helm diff v3.1.1
KOPS version 1.15
kubernetes version 1.15

Example of helmsman script is 

```
#version: v3.4.0

# context defines the context of this Desired State File.
# It is used to allow Helmsman identify which releases are managed by which DSF.
# Therefore, it is important that each DSF uses a unique context.
context: service-account-context   # defaults to "default" if not provided

# metadata -- add as many key/value pairs as you want
metadata:
  scope: "company"
  maintainer: "company  maintainer"
  description: "company description"

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster.
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key and caClient for the client certificate
# certificates:
  #caClient: "gs://mybucket/client.crt" # GCS bucket path
  #caCrt: "gs://mybucket/ca.crt" # valid local file relative path to the DSF file
  #caKey: "../ca.key" # valid local file relative path

settings:
#  kubeContext: "minikube" # will try connect to this context first, if it does not exist, it will be created using the details below
  kubeContext: "prod@company" # will try connect to this context first, if it does not exist, it will be created using the details below
  slackWebhook:  "https://app.slack.com" # or your slack webhook url
```

hoping somebody can point me to the correct direction here since we really dont have much to go with since the script fails with no error logs.
