### ISSUE TITLE
[hooks] Key "postInstall" already set in map

### ISSUE THREAD

**Issue by all4innov** [Praqma/helmsman#475]
As a replacement for these two kubectl commands at cluster level

```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.14.3/cert-manager.crds.yaml
kubectl apply -f cert-manager/clusterissuer.yml
```
the new globalHooks feature was adopted:

```
settings:
  kubeContext: pop-paris
  globalHooks:
    # successCondition: "Initialized"
    # deleteOnSuccess: true
    postInstall: "https://github.com/jetstack/cert-manager/releases/download/v0.14.3/cert-manager.crds.yaml"
    postInstall: "cert-manager/clusterissuer.yml"
```

The problem is that the second postInstall line was not accepted and here the error:
```
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v3.4.1
A Helm-Charts-as-Code tool.

2020-05-18 15:50:36 CRITICAL: yaml: unmarshal errors:
  line 15: key "postInstall" already set in map
```
