### ISSUE TITLE
helm show fails with private helm repos

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/helmsman#479]
`helm show` was introduced in #411 .. this works fine for public helm repos. For private repos, it requires additional `--username` and `--password` args. 

To reproduce: 

```toml
[helmRepos]
  myrepo = "https://$ARTIFACTORY_USER:$ARTIFACTORY_PASS@myrepo.jfrog.io/myorg/myorg-helm-virtual"

[apps]
  [apps.test]
    namespace = "default"
    enabled = true
    chart = "myrepo/my-app"
    version = "0.3.9"
    valuesFile= "test-values.yaml"
    wait = true
```
```bash
$ helmsman --debug -f dsf.toml 
...
2020-05-28 10:46:07 DEBUG: helm show chart myrepo/my-app
2020-05-28 10:46:08 CRITICAL: While getting chart information: Error: failed to download "myrepo/my-app" (hint: running `helm repo update` may help)
```

```bash
helm show chart myrepo/my-app
Error: failed to download "myrepo/my-app" (hint: running `helm repo update` may help)

helm show chart myrepo/my-app --username $USER --password $PASS
apiVersion: v1
description: A Helm chart test apps in Kubernetes
name: my-app
version: 0.3.9
```
helm version: v3.2.1
