### ISSUE TITLE
Can't destroy a deployment in kube-system

### ISSUE THREAD

**Issue by JonathanLachapelle** [Praqma/helmsman#483]
Using helmsman Helmsman version: v3.4.2

I have a deployment, I can deploy it successfully but when I try to destroy it, only the ressources that are not part of the kube-system are destroyed. If instead I use another namespace instead of kube-system, everything work well. It's like somthing is preventing me from destroying ressources I created in kube-system

Here's the state file : 

```
appsTemplates:
  default: &template
      valuesFile: ""
      protected: false
      wait: true

namespaces:
  prometheus-operator:
  datadog:

apps:
  prometheus-operator:
    <<: *template
    namespace: prometheus-operator
    enabled: true
    chart: stable/prometheus-operator
    version: 8.13.8

  metrics-server:
    <<: *template
    namespace: kube-system
    enabled: true
    chart: stable/metrics-server
    version: 2.11.1
    valuesFile: ./metrics-server/values.yaml

  cluster-autoscaler:
    <<: *template
    namespace: kube-system
    enabled: true
    chart: stable/cluster-autoscaler
    version: 7.3.2
    valuesFile: ./cluster-autoscaler/values.yaml

  datadog:
    <<: *template
    namespace: datadog
    enabled: true
    chart: stable/datadog
    version: 2.3.8
    valuesFile: ./datadog/values.yaml

  vpa:
    <<: *template
    namespace: kube-system
    enabled: true
    chart: cowboysysop/vertical-pod-autoscaler
    version: 1.4.2
  
  aws-ebs-csi-driver:
    <<: *template
    namespace: kube-system
    enabled: true
    chart: nexus/aws-ebs-csi-driver
    version: 0.3.0
    valuesFile: ./aws-ebs-csi-driver/values.yaml

```

Here's the result : 
2020-06-01 19:04:55 INFO: validating environment variables in helm-deployment/helmsman-deployment.yaml
2020-06-01 19:04:55 INFO: validating environment variables in /helm/.helmsman-tmp/tmp087440706/432815510values.yaml
2020-06-01 19:04:55 INFO: validating environment variables in /helm/.helmsman-tmp/tmp087440706/475157587values.yaml
2020-06-01 19:04:55 INFO: Parsed YAML [[ helm-deployment/helmsman-deployment.yaml ]] successfully and found [ 6 ] apps
2020-06-01 19:04:55 INFO: Validating desired state definition...
2020-06-01 19:04:55 INFO: Setting up kubectl...
2020-06-01 19:04:55 INFO: Setting up helm...
2020-06-01 19:04:57 INFO: Setting up namespaces...
2020-06-01 19:04:58 INFO: Validating charts...
2020-06-01 19:05:00 WARNING: Destroy flag is enabled. Your releases will be deleted!
2020-06-01 19:05:00 INFO: Preparing plan...
2020-06-01 19:05:00 INFO: Acquiring current Helm state from cluster...
2020-06-01 19:05:06 INFO: Checking if any Helmsman managed releases are no longer tracked by your desired state ...
2020-06-01 19:05:07 INFO: No untracked releases found
2020-06-01 19:05:07 NOTICE: -------- PLAN starts here --------------
2020-06-01 19:05:07 WARNING: Release [ prometheus-operator ] will be DELETED (destroy flag enabled). -- priority: 0
2020-06-01 19:05:07 WARNING: Release [ datadog ] will be DELETED (destroy flag enabled). -- priority: 0
2020-06-01 19:05:07 NOTICE: -------- PLAN ends here --------------
2020-06-01 19:05:07 INFO: Executing plan... 
2020-06-01 19:05:07 NOTICE: Delete release [ prometheus-operator ] in namespace [ prometheus-operator ]
2020-06-01 19:05:12 NOTICE: release "prometheus-operator" uninstalled

2020-06-01 19:05:12 NOTICE: Finished: Delete release [ prometheus-operator ] in namespace [ prometheus-operator ]
2020-06-01 19:05:12 NOTICE: Delete release [ datadog ] in namespace [ datadog ]
2020-06-01 19:05:15 NOTICE: release "datadog" uninstalled

2020-06-01 19:05:15 NOTICE: Finished: Delete release [ datadog ] in namespace [ datadog ]
2020-06-01 19:05:15 INFO: Plan applied
