### ISSUE TITLE
ups is not in the target group and therefore context and labels are not changed.

### ISSUE THREAD

**Issue by Kylepossible** [Praqma/helmsman#509]
I'm having an issue deploying a certain DSF with the `-group` command. 

I have a desired state file that looks as such. 

```
metadata:
  description: The LDPS Desired State Configuration

context: ldps-helmsman

namespaces:
  ldps:

helmRepos:
  redacted: s3://my-kitchen/helm

apps:
  ldps:
    name: ldps-helmsman
    description: "The LDPS Service"
    namespace: ldps
    chart: redacted/luna-ldps
    version: 19.5.0
    enabled: true
    group: ldps-helmsman
    valuesFiles:
      - values/ldps-values.yaml
      - values/tolerations.yaml
```

I am running this exact command `helmsman -apply -f desired-state.yaml -group ldps-helmsman  -debug -migrate-context  --subst-env-values -subst-ssm-values` 

I am receiving `ldps-helmsman is not in the target group and therefore context and labels are not changed.`  as well as 

`2020-09-08 16:42:07 INFO: No untracked releases found
2020-09-08 16:42:07 NOTICE: -------- PLAN starts here --------------
2020-09-08 16:42:07 INFO: Release [ ldps-helmsman ] ignored -- priority: 0
2020-09-08 16:42:07 NOTICE: -------- PLAN ends here --------------
2020-09-08 16:42:07 INFO: Printing the commands of the current plan ...`

If I omit the `-group` command the release installs without issue. I am confused as to why this specific DSF the `group: ldps-helmsman` is not in the "target group".  I have very similar looking DSF files for other applications and the group command does not cause this issue. 

I'm not sure what could be causing my issue?
