### ISSUE TITLE
Support local charts on file system

### ISSUE THREAD

**Issue by flypenguin** [Praqma/helmsman#51]
According to the desired state docs (for the `chart` field) it must contain `repo` and `chart`. 
I would like to be able to deploy a chart from the local file system as well.

Example:

```yaml
apps:
  jenkins:
    name: "mychart
    description: "My Local Chart
    namespace: "staging"
    enabled: true
    chart: "./mychart"
```
