### ISSUE TITLE
 Error: failed to download "jupyterhub/binderhub" 

### ISSUE THREAD

**Issue by ctr26** [Praqma/helmsman#512]
Hi all,

I'm trying to incorporate helmsman into my CI/CD for binderhub, unfortunately even a bare bones config fails "While getting chart information"

Looking at the debug I think the issue is that helmsman runs `helm show chart jupyterhub/binderhub` without a version number and for binderhub that returns nothing:

`helm show chart jupyterhub/binderhub --version 0.2.0-n219.hbc17443`

```
apiVersion: v1
dependencies:
- name: jupyterhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 0.9.0
description: A helm chart to install Binder
name: binderhub
version: 0.2.0-n219.hbc17443
```

`helm show chart jupyterhub/binderhub`

`Error: failed to download "jupyterhub/binderhub" (hint: running `helm repo update` may help)`

Here's my config:

```
namespaces:
  binderhub-staging:

helmRepos:
  jupyterhub: "https://jupyterhub.github.io/helm-chart/"

apps:
  binderhub-staging:
    valuesFiles:
      - "binderhub/config.yaml"
      - "binderhub/secret.yaml"
    name: "binderhub-staging"
    namespace: "binderhub-staging"
    chart: "jupyterhub/binderhub"
    version: "0.2.0-n219.hbc17443"
    priority: -3

```
