### ISSUE TITLE
Upgrades fail when using kube-system Tiller

### ISSUE THREAD

**Issue by gorzek** [Praqma/helmsman#57]
Found what seems to be an easily reproducible bug:

1. Install a release with helmsman using only the kube-system Tiller (no per-namespace Tillers)
2. Update the version number for an app in the helmsman configuration
3. Apply helmsman configuration again

Two things happen: the release is found to not exist, because helmReleaseExists checks for [release]-[tiller-namespace], when it should actually look for [release]-[installed-namespace]; so it attempts a new installation, which fails because the release is already present. It fails to do a proper upgrade check and then upgrade the release.

**Comment by sami-alajrami** [comment]
@gorzek  I am assuming this is on helmsman v1.4.0-rc? 
also could you please share a snippet of your desired state file, or  at least the namespaces sections?

**Comment by gorzek** [comment]
Yes, this happens in 1.4.0-rc.

```
settings:
  kubeContext: "test-001"
  storageBackend: "configMap"

namespaces:
  infra:
    protected: false
    installTiller: false

helmRepos:
  stable: "https://kubernetes-charts.storage.googleapis.com"
  incubator: "http://storage.googleapis.com/kubernetes-charts-incubator"

apps:
  chartmuseum:
    name: "inf-chartmuseum"
    description: "chartmuseum"
    namespace: "infra"
    enabled: true
    chart: "stable/chartmuseum"
    version: "1.5.0"
    valuesFile: "chartmuseum.yaml"
    purge: true
    test: false
    protected: false
    priority: -95
    wait: true
```
