### ISSUE TITLE
How to deploy multiple crds in helmsman dsf file pre-install hook?

### ISSUE THREAD

**Issue by KR411-prog** [Praqma/helmsman#570]
How to deploy multiple crds in helmsman dsf file pre-install hook? I tried like below..but it is throwing error,

```
kube-prometheus-stack:
    enabled: true
    hooks:
      preInstall: "https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-12.11.3/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml"
      preInstall: "https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-12.11.3/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml"
      preInstall: "https://raw.githubusercontent.com/prometheus-community/helm-chart
```
