### ISSUE TITLE
Helmsman preInstall hook is not executing script

### ISSUE THREAD

**Issue by KR411-prog** [Praqma/helmsman#571]
I am trying below command in dsf file to execute a script,
```
  kube-prometheus-stack:
    enabled: true
    hooks:
      preInstall: "./add-ons/kube-prometheus-stack/kubeprometheus-12x-crds.sh"
```
Content of the script:
```
#!/bin/bash

CRD_VERSION=12.11.3
crds="alertmanagerconfigs alertmanagers podmonitors probes prometheuses prometheusrules servicemonitors thanosrulers"
for crd in $crds; do
  kubectl apply -f "https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-$CRD_VERSION/charts/kube-prometheus-stack/crds/crd-$crd.yaml"
done
```

But the error is,
`CRITICAL: apps validation failed -- for app [kube-prometheus-stack ]. config/add-ons/kube-prometheus-stack/kubeprometheus-12x-crds.sh must be of one the following file formats: .yaml, .yml, .json`

Helmsman version : 3.6.2
As per the document , Shell script can be executed in preinstall hook.But not sure why its only expecting yaml,json.
What am I missing here? Does shell script work in preinstall hook?
