### ISSUE TITLE
Helmsman preinstall hook not working for shell script

### ISSUE THREAD

**Issue by KR411-prog** [Praqma/helmsman#573]
I am trying below command in dsf file to execute a script,
```
  kube-prometheus-stack:
    enabled: true
    hooks:
      preInstall: "./add-ons/kube-prometheus-stack/kubeprometheus-12x-crds.sh"
```
Content of the script:
```
#!/bin/bash

CRD_VERSION=12.11.3
crds="alertmanagerconfigs alertmanagers podmonitors probes prometheuses prometheusrules servicemonitors thanosrulers"
for crd in $crds; do
  kubectl apply -f "https://raw.githubusercontent.com/prometheus-community/helm-charts/kube-prometheus-stack-$CRD_VERSION/charts/kube-prometheus-stack/crds/crd-$crd.yaml"
done
```

But the error is,
`CRITICAL: apps validation failed -- for app [kube-prometheus-stack ]. config/add-ons/kube-prometheus-stack/kubeprometheus-12x-crds.sh must be of one the following file formats: .yaml, .yml, .json`

Helmsman version : 3.6.2
As per the document , Shell script can be executed in preinstall hook.But not sure why its only expecting yaml,json.
What am I missing here? Does shell script work in preinstall hook?

**Comment by luisdavim** [comment]
Hi, is the file you're passing as the hook set as executable?
You can also try:

```yaml
  kube-prometheus-stack:
    enabled: true
    hooks:
      preInstall: "./add-ons/kube-prometheus-stack/kubeprometheus-12x-crds.sh"
```

But if all your scrip it doing is calling `kubectl apply` you can also try placing all your `yaml` manifests into a single file separated by `---` and just pass the path to that `yaml` file as the hook.

**Comment by luisdavim** [comment]
BTW, what's the version of helmsman you're using? Shell hooks where only introduced recently and the version you're using might not support them yet....

**Comment by luisdavim** [comment]
Can you make sure your script is set as executable and try `v3.6.4` ? There was a fix there regarding the hook file paths.

**Comment by mqmr** [comment]
Hello @luisdavim,

Could you please tell if it's always necessary to specify bash before a script like it's defined in your example?

**Comment by luisdavim** [comment]
Only if the file you're trying to execute is not executable.

**Comment by mqmr** [comment]
Thank you for a swift response.

I've been trying to deal with an issue with using a script defined in a preInstall hook in an upper-level DSF. Here's an example of what I have:
```
helmsman -v
Helmsman version: v3.6.6

helmsman --no-fancy --target ingress -f common/dsf.yaml -e common/common.env -f cluster01/dsf.yaml -e cluster01/cluster.env
2021-03-26 08:41:26 INFO: validating environment variables in common/dsf.yaml
2021-03-26 08:41:26 INFO: Parsed YAML [[ common/dsf.yaml ]] successfully and found [ 22 ] apps
2021-03-26 08:41:26 INFO: validating environment variables in cluster01/dsf.yaml
2021-03-26 08:41:26 INFO: Parsed YAML [[ cluster01/dsf.yaml ]] successfully and found [ 14 ] apps
2021-03-26 08:41:26 INFO: Validating desired state definition
2021-03-26 08:41:26 CRITICAL: apps validation failed -- for app [ingress ]. invalid hook manifest: scripts/get-ip must be valid relative (from dsf file) file path: stat scripts/get-ip: no such file or directory
```

definition of the app in the common DSF: 
```
❯ rg -A 10 -N ingress common/dsf.yaml
  ingress:
    namespace: default
    enabled: false
    chart: stable/nginx-ingress
    version: 1.43.1
    hooks:
      preInstall: scripts/get-ip
      preUpgrade: scripts/get-ip
    valuesFiles:
      - values/common-ingress.yaml
      - values/ingress.yaml
```

definition of the same app in the cluster specific DSF: 
```
rg -A 3 -N ingress cluster01/dsf.yaml
  ingress:
    enabled: true
    valuesFiles:
      - values/ingress.yaml
```

A script is under common/scripts directory and has an executable bit:
```
ls -l common/scripts/get-ip
-rwxr-xr-x 1 keepclean staff 182 Mar 25 20:56 common/scripts/get-ip
```

In the common DSF I also have another example of a hook usage:
```
rg -A 8 -N cert-manager common/dsf.yaml
  cert-manager:
    namespace: system
    enabled: false
    chart: jetstack/cert-manager
    version: v0.16.1
    valuesFiles:
      - values/cert-manager.yaml
    hooks:
      preInstall: crds/cert-manager.yaml
```
and I've never seen an issue helmsman complains about that hook.

Could you please tell if there's any additional limitation to why a hook with a script cannot be found by helmsman?

Thank you in advance.
