### ISSUE TITLE
Environment value substitution inconsistencies and undocumented breaking changes in how they are evaluated

### ISSUE THREAD

**Issue by bergerx** [Praqma/helmsman#583]
We have Helmsman 3.1.0 in our pipelines, and have been thinking about moving to the latest (3.6.4 as of now).
But we hit an undocumented breaking change in recent helmsman versions.
And as a result, I found Helmsmans environment value substitution is not consistent.

# Test Environment Setup

I prepared a test env to see how the two Helmsman versions are evaluating environment variables.

List of different scenarios to cover:
* **where var is defined**: "Var in file" (InFile), or "Var as ENV" (AsEnv)
* **where var is used**: "As Set in DSF" (UsedInDsf), or "As helm variables File" (UsedInVars)
* **whats the value of variable**: "Missing" (MissingVar), "EmptyVar" (EmptyVar), or "some value" (SomeVar)
* **how the var is used**: Regular (Regular), or Curly Braces (Curly)
So we have 2*2*2*3 = 24 cases in total

Prepare the test environment:

```bash
mkdir /tmp/test
cd /tmp/test

curl -L https://github.com/Praqma/helmsman/releases/download/v3.6.4/helmsman_3.6.4_darwin_amd64.tar.gz | tar zxvf - helmsman; mv helmsman helmsman-3.6.4
curl -L https://github.com/Praqma/helmsman/releases/download/v3.1.0/helmsman_3.1.0_darwin_amd64.tar.gz | tar zxvf - helmsman; mv helmsman helmsman-3.1.0

helm create test-chart

cat > env.yaml <<EOF
SOME_VAR_IN_FILE: awesome-value-in-file
EMPTY_VAR_IN_FILE: ''
# MISSING_VAR_IN_FILE: 
EOF

export SOME_VAR_AS_ENV=awesome-value-as-env
export EMPTY_VAR_AS_ENV=
#export MISSING_VAR_AS_ENV=

cat > helmsman.yaml <<EOF
namespaces:
  test:
apps:
  ingress:
    namespace: test
    enabled: true
    chart: ./test-chart
    version: 0.1.0
    valuesFiles:
    - vars.yaml
    set:
      RegularMissingVarInFileUsedInDsf:   \$MISSING_VAR_IN_FILE
      RegularMissingVarAsEnvUsedInDsf:    \$MISSING_VAR_AS_ENV
      CurlyMissingVarInFileUsedInDsf:     \${MISSING_VAR_IN_FILE}
      CurlyMissingVarAsEnvUsedInDsf:      \${MISSING_VAR_AS_ENV}
      RegularEmptyVarInFileUsedInDsf:     \$EMPTY_VAR_IN_FILE
      RegularEmptyVarAsEnvUsedInDsf:      \$EMPTY_VAR_AS_ENV
      CurlyEmptyVarInFileUsedInDsf:       \${EMPTY_VAR_IN_FILE}
      CurlyEmptyVarAsEnvUsedInDsf:        \${EMPTY_VAR_AS_ENV}
      RegularExistingVarInFileUsedInDsf:  \$SOME_VAR_IN_FILE
      RegularExistingVarAsEnvUsedInDsf:   \$SOME_VAR_AS_ENV     
      CurlyExistingVarInFileUsedInDsf:    \${SOME_VAR_IN_FILE}
      CurlyExistingVarAsEnvUsedInDsf:     \${SOME_VAR_AS_ENV}
EOF

cat > vars.yaml <<EOF
This is from Helmsman \$HELMSMAN_VERSION:

RegularMissingVarInFileUsedInVars:   \$MISSING_VAR_IN_FILE
RegularMissingVarAsEnvUsedInVars:    \$MISSING_VAR_AS_ENV
CurlyMissingVarInFileUsedInVars:     \${MISSING_VAR_IN_FILE}
CurlyMissingVarAsEnvUsedInVars:      \${MISSING_VAR_AS_ENV}
RegularEmptyVarInFileUsedInVars:     \$EMPTY_VAR_IN_FILE
RegularEmptyVarAsEnvUsedInVars:      \$EMPTY_VAR_AS_ENV
CurlyEmptyVarInFileUsedInVars:       \${EMPTY_VAR_IN_FILE}
CurlyEmptyVarAsEnvUsedInVars:        \${EMPTY_VAR_AS_ENV}
RegularExistingVarInFileUsedInVars:  \$SOME_VAR_IN_FILE
RegularExistingVarAsEnvUsedInVars:   \$SOME_VAR_AS_ENV     
CurlyExistingVarInFileUsedInVars:    \${SOME_VAR_IN_FILE}
CurlyExistingVarAsEnvUsedInVars:     \${SOME_VAR_AS_ENV}

EOF
```

# 3.1.0 Works Fine

Helmsman 3.1.0 works ok with these inputs:
```bash
export HELMSMAN_VERSION=3.1.0
kubectl delete ns test
./helmsman-$HELMSMAN_VERSION \
  -e env.yaml \
  -f helmsman.yaml \
  --subst-env-values \
  --apply
helm get values -n test ingress > helmsman-${HELMSMAN_VERSION}-values.out
```

# 3.6.4 Fails with an unset variable message

Helmsman 3.6.4 is not behaving same, and no breaking changes mentioned in the changelog:
```bash
export HELMSMAN_VERSION=3.6.4
kubectl delete ns test
./helmsman-$HELMSMAN_VERSION \
  -e env.yaml \
  -f helmsman.yaml \
  --subst-env-values \
  --apply
helm get values -n test ingress > helmsman-${HELMSMAN_VERSION}-values.out
```

Here how 3.6.4 fails:
```
2021-03-02 14:44:49 CRITICAL: $MISSING_VAR_IN_FILE is used as an env variable but is currently unset. Either set it or escape it like so: $$MISSING_VAR_IN_FILE
```
I had to comment out the missing variable usages in the DSF file (but the same is not needed for values files):

```diff
diff -u helmsman.yaml-3.1.0 helmsman.yaml-3.6.4
--- helmsman.yaml-3.1.0	2021-03-02 15:04:11.465668739 +0000
+++ helmsman.yaml-3.6.4	2021-03-02 15:03:55.391831585 +0000
@@ -9,10 +9,10 @@
     valuesFiles:
     - vars.yaml
     set:
-      RegularMissingVarInFileUsedInDsf:   $MISSING_VAR_IN_FILE
-      RegularMissingVarAsEnvUsedInDsf:    $MISSING_VAR_AS_ENV
-      CurlyMissingVarInFileUsedInDsf:     ${MISSING_VAR_IN_FILE}
-      CurlyMissingVarAsEnvUsedInDsf:      ${MISSING_VAR_AS_ENV}
+      #RegularMissingVarInFileUsedInDsf:   $MISSING_VAR_IN_FILE
+      #RegularMissingVarAsEnvUsedInDsf:    $MISSING_VAR_AS_ENV
+      #CurlyMissingVarInFileUsedInDsf:     ${MISSING_VAR_IN_FILE}
+      #CurlyMissingVarAsEnvUsedInDsf:      ${MISSING_VAR_AS_ENV}
       RegularEmptyVarInFileUsedInDsf:     $EMPTY_VAR_IN_FILE
       RegularEmptyVarAsEnvUsedInDsf:      $EMPTY_VAR_AS_ENV
       CurlyEmptyVarInFileUsedInDsf:       ${EMPTY_VAR_IN_FILE}
```

After commenting out the missing vars in DSF for helmsman 3.6.4 seems like how they were evaluated did not change:

```diff
$ diff -u helmsman-*-values.out
--- helmsman-3.1.0-values.out	2021-03-02 14:55:13.224487907 +0000
+++ helmsman-3.6.4-values.out	2021-03-02 14:57:39.674318571 +0000
@@ -7,9 +7,7 @@
 CurlyExistingVarAsEnvUsedInVars: awesome-value-as-env
 CurlyExistingVarInFileUsedInDsf: awesome-value-in-file
 CurlyExistingVarInFileUsedInVars: awesome-value-in-file
-CurlyMissingVarAsEnvUsedInDsf: ""
 CurlyMissingVarAsEnvUsedInVars: null
-CurlyMissingVarInFileUsedInDsf: ""
 CurlyMissingVarInFileUsedInVars: null
 RegularEmptyVarAsEnvUsedInDsf: ""
 RegularEmptyVarAsEnvUsedInVars: null
@@ -19,8 +17,6 @@
 RegularExistingVarAsEnvUsedInVars: awesome-value-as-env
 RegularExistingVarInFileUsedInDsf: awesome-value-in-file
 RegularExistingVarInFileUsedInVars: awesome-value-in-file
-RegularMissingVarAsEnvUsedInDsf: ""
 RegularMissingVarAsEnvUsedInVars: null
-RegularMissingVarInFileUsedInDsf: ""
 RegularMissingVarInFileUsedInVars: null
-This is from Helmsman 3.1.0: null
+This is from Helmsman 3.6.4: null
```

# Inconsistent substitution of Empty/Missing environment variables based on where they are used

Here are the contents of 3.1.0 (3.6.4. is just missing some vars as shown above):
```yaml
USER-SUPPLIED VALUES:
CurlyEmptyVarAsEnvUsedInDsf: ""
CurlyEmptyVarAsEnvUsedInVars: null
CurlyEmptyVarInFileUsedInDsf: ""
CurlyEmptyVarInFileUsedInVars: null
CurlyExistingVarAsEnvUsedInDsf: awesome-value-as-env
CurlyExistingVarAsEnvUsedInVars: awesome-value-as-env
CurlyExistingVarInFileUsedInDsf: awesome-value-in-file
CurlyExistingVarInFileUsedInVars: awesome-value-in-file
CurlyMissingVarAsEnvUsedInDsf: ""
CurlyMissingVarAsEnvUsedInVars: null
CurlyMissingVarInFileUsedInDsf: ""
CurlyMissingVarInFileUsedInVars: null
RegularEmptyVarAsEnvUsedInDsf: ""
RegularEmptyVarAsEnvUsedInVars: null
RegularEmptyVarInFileUsedInDsf: ""
RegularEmptyVarInFileUsedInVars: null
RegularExistingVarAsEnvUsedInDsf: awesome-value-as-env
RegularExistingVarAsEnvUsedInVars: awesome-value-as-env
RegularExistingVarInFileUsedInDsf: awesome-value-in-file
RegularExistingVarInFileUsedInVars: awesome-value-in-file
RegularMissingVarAsEnvUsedInDsf: ""
RegularMissingVarAsEnvUsedInVars: null
RegularMissingVarInFileUsedInDsf: ""
RegularMissingVarInFileUsedInVars: null
This is from Helmsman 3.1.0: null
```
