### ISSUE TITLE
Apply values file with OCI registry 

### ISSUE THREAD

**Issue by relative-progressio** [Praqma/helmsman#616]
Hi all,

We want to deploy our helm charts (stored in Azure Container Registry) via helmsman to our k8s cluster. Azure Container Registry is able host helm charts because it has OCI registries support, see [1] for details.
Helmsmen is also supporting OCI registries since version 3.7.0. :)
We updated to version 3.7.1.

We adapted our helmsman file according to the provided documentation [2]

```
apps:
    myapp:
      namespace: "mynamespace" # maps to the namespace as defined in namespaces above
      enabled: true # change to false if you want to delete this app release empty: false:
      chart: "oci://myacr.azurecr.io/helm/myapp" # changing the chart name means delete and recreate this chart
      version: "0.1.27-639e65e-staging" # chart version
      ### Optional values below
      valuesFile: "" # leaving it empty uses the default chart values
      test: false
      protected: false
      wait: true
      helmFlags: 
        - "--atomic"
        - "--cleanup-on-fail"
        - "--create-namespace"
      set:
        "nodeSelector.nodetype": application
```

That seams to work, since helmsman is logging the following:
`2021-06-22 11:21:31 DEBUG: helm upgrade myapp /home/builduser/buildagent/_work/18/s/k8s/helmsman/.helmsman-tmp/tmp471897751/myapp --install --version 0.1.27-639e65e-staging --namespace mynamespace --set nodeSelector.nodetype=application --wait --debug  --atomic --cleanup-on-fail --create-namespace
`
However, our app needs specified values files, so we need to use the `valuesFiles `property from the desired state file:

```
apps:
    myapp:
      namespace: " mynamespace " # maps to the namespace as defined in namespaces above
      enabled: true # change to false if you want to delete this app release empty: false:
      chart: "oci:// myacr.azurecr.io/helm/myapp"
      version: "0.1.27-639e65e-staging" # chart version
      ### Optional values below
      valuesFiles: ["values.yaml", "values-staging.yaml"]
      test: false
      protected: false
      wait: true
      helmFlags: 
        - "--atomic"
        - "--cleanup-on-fail"
        - "--create-namespace"
      set:
        "nodeSelector.nodetype": application

```
Declaring it in the following way, leads to the fact that helmsman is searching for files from the local path and not pulled from the registry.

`2021-06-22 11:29:27 CRITICAL: could not stat /home/builduser/buildagent/_work/18/s/k8s/helmsman/values.yaml : stat /home/builduser/buildagent/_work/18/s/k8s/helmsman/values.yaml: no such file or directory 
`
So with the next try, we tried to reference the OCI registry itself:

```
apps:
    myapp:
      namespace: "mynamespace" # maps to the namespace as defined in namespaces above
      enabled: true # change to false if you want to delete this app release empty: false:
      chart: "oci://myacr.azurecr.io/helm/myapp"
      version: "0.1.27-639e65e-staging" # chart version
      ### Optional values below
      valuesFiles: ["oci://myacr.azurecr.io/helm/myapp/values.yaml", "oci:// myacr.azurecr.io /helm/myapp/values-staging.yaml"] 
      test: false
      protected: false
      wait: true
      helmFlags: 
        - "--atomic"
        - "--cleanup-on-fail"
        - "--create-namespace"
      set:
        "nodeSelector.nodetype": application

```
The log shows that a pull and a helm chart export is happening to a certain directory, but it is not able to find the values.yaml file.

```
2021-06-22 12:53:01 DEBUG: helm chart pull myacr.azurecr.io/helm/myapp/values.yaml 
2021-06-22 12:53:01 DEBUG: helm chart pull myacr.azurecr.io/helm/myapp/values-staging.yaml 
2021-06-22 12:53:02 DEBUG: helm chart pull myacr.azurecr.io/helm/myapp:0.1.27-639e65e-staging 
2021-06-22 12:53:02 DEBUG: helm chart export myacr.azurecr.io/helm/myapp:0.1.27-639e65e-staging -d /home/builduser/buildagent/_work/18/s/k8s/helmsman/.helmsman-tmp/tmp531744099 
2021-06-22 12:53:02 CRITICAL: open /home/builduser/buildagent/_work/18/s/k8s/helmsman/.helmsman-tmp/tmp531744099/values.yaml: no such file or directory 

```
When we investigate the directory, we can see the following structure:

```
-rw------- 1 builduser builduser    0 Jun 22 12:53 094120845values-staging.yaml
-rw------- 1 builduser builduser    0 Jun 22 12:53 463901030values.yaml
-rw------- 1 builduser builduser    0 Jun 22 12:53 660372872myapp:0.1.27-639e65e-staging
drwxr-xr-x 3 builduser builduser 4096 Jun 22 12:53 myapp/

```
Note that there is a values.yaml file but with a random number prefix and the file is empty, since `cat `does not return anything. 
However, there is a folder (the helm chart “myapp” with all the files in) available, so with our last try, we tried to navigate to that folder:

```
apps:
    myapp:
      namespace: "mynamespace" # maps to the namespace as defined in namespaces above
      enabled: true # change to false if you want to delete this app release empty: false:
      chart: "oci://myacr.azurecr.io/helm/myapp" # changing the chart name means delete and recreate this chart
      version: "0.1.27-639e65e-staging" # chart version
      ### Optional values below
      valuesFiles: ["oci://myacr.azurecr.io/helm/myapp/myapp/values.yaml", "oci://myacr.azurecr.io/helm/myapp/myapp/values-staging.yaml"] # leaving it empty uses the default chart values
      test: false
      protected: false
      wait: true
      helmFlags: 
        - "--atomic"
        - "--cleanup-on-fail"
        - "--create-namespace"
      set:
        "nodeSelector.nodetype": application
```

Sadly, that did not change the outcome. 

```
2021-06-22 13:12:42 DEBUG: helm version --short --client
2021-06-22 13:12:42 DEBUG: helm version --short --client
2021-06-22 13:12:42 DEBUG: kubectl version --short --client
2021-06-22 13:12:42 DEBUG: helm plugin list
2021-06-22 13:12:42 DEBUG: helm chart pull myacr.azurecr.io/helm/myapp/myapp/values.yaml
2021-06-22 13:12:42 DEBUG: helm chart pull myacr.azurecr.io/helm/myapp/myapp/values-staging.yaml
2021-06-22 13:12:42 DEBUG: helm chart pull myacr.azurecr.io/helm/myapp:0.1.27-639e65e-staging
2021-06-22 13:12:42 DEBUG: helm chart export myacr.azurecr.io/helm/myapp:0.1.27-639e65e-staging -d /home/builduser/buildagent/_work/18/s/k8s/helmsman/.helmsman-tmp/tmp953800554
2021-06-22 13:12:42 CRITICAL: open /home/builduser/buildagent/_work/18/s/k8s/helmsman/.helmsman-tmp/tmp953800554/values.yaml: no such file or directory

```

So, our question is basically: What went wrong and how to specify the values.yaml files in order to be pulled from the OCI registry.

Help on that would be much appreciated. :) 

[1] https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos  
[2] https://github.com/Praqma/helmsman/blob/master/docs/how_to/helm_repos/oci.md

**Comment by luisdavim** [comment]
I don't think OCI values is a thing, how did you push them to  the repository? Normally values are not stored in helm repos they would be stored in git along with the Helmsman files or the application.
What helmsman does support is passing a URL for the values files so you can try that...

**Comment by relative-progressio** [comment]
Hi,

Sorry, if I was not clear enough, the values files are not directly stored on the OCI registry, there are within the folder of the chart (just like the Chart.yml and so on):

```
drwxr-xr-x 3 builduser builduser 4096 Jun 22 13:12 ./
drwx------ 3 builduser builduser 4096 Jun 22 13:12 ../
-rw-r--r-- 1 builduser builduser  333 Jun 22 13:12 .helmignore
-rw-r--r-- 1 builduser builduser  165 Jun 22 13:12 Chart.yaml
drwxr-xr-x 2 builduser builduser 4096 Jun 22 13:12 templates/
-rw-r--r-- 1 builduser builduser  321 Jun 22 13:12 values-dev.yaml
-rw-r--r-- 1 builduser builduser  305 Jun 22 13:12 values-prod.yaml
-rw-r--r-- 1 builduser builduser  314 Jun 22 13:12 values-staging.yaml
-rw-r--r-- 1 builduser builduser  331 Jun 22 13:12 values-test.yaml
-rw-r--r-- 1 builduser builduser 1194 Jun 22 13:12 values.yaml
```

They got pushed together with all the other files of the chart via `helm chart push` [3]

So, my assumption was that helmsman is able to pick the files up once it's exported

[3] https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#push-chart-to-registry

**Comment by luisdavim** [comment]
oh, I see, that's not really supported, we assume the paths for any file in the Helmsman DSF are relative to that file if they are not absolute, I don't think that what you're trying to do is a common pattern so I don't think it's worth supporting.

But if you're bundling the values files with your chart why not just use the default values for that? if you want to switch on the env you could have a map with the per env config and an extra value that would determine what env to use and then you can use set to override that for each environment, something like:

```yaml
# Common configs
something: true
env: dev

# dev config
dev:
  foo: bar
  #...

# prod config
prod:
  foo: barz
  #...
```

and then in your templates you can use something like

```
{{- $env := .Values.env -}}
foo: {{ .Values.$env.foo }}
```

or you can simply specify the values in your Helmsman file or store the values together with the helmsman files....
