### ISSUE TITLE
Change Tiller Url tiller-image

### ISSUE THREAD

**Issue by mhobotpplnet** [Praqma/helmsman#623]
Got bit of dilemma with CD regards to installing charts with helmsman, basically it calls the helm2.16 init .1 which by default installs tiller 'installTiller=true'. 

Issue is that tiller image thats getting it from is on old google cloud infrastructure. Is there a way to make it in template so it uses different location for same image ? 

Say: --tiller-image=ghcr.io/helm/tiller:v2.16.1

currently runs:

`2021/08/17 17:05:44 VERBOSE: helm init --force-upgrade --tiller-namespace mynamespace --history-max 5 --service-account tiller --override 'spec.template.spec.containers[0].resources.limits.memory'='2Gi' --override 'spec.template.spec.containers[0].resources.limits.cpu'='1' --override 'spec.template.spec.containers[0].resources.requests.memory'='768Mi' --override 'spec.template.spec.containers[0].resources.requests.cpu'='300m'`

Settings:

```
namespaces:
  mynamespace:
    installTiller: true
    quotas:
      limits:
        cpu: '100'
        memory: 300Gi
      pods: '100'
      requests:
        cpu: '40'
        memory: 200Gi
    tillerMaxHistory: 5
    tillerResources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 768Mi
```
I can force out script to add --tiller-image=blablabla , but I want to really have it in template , almost done with going with helm3 so am going to be glad when this is over.
