### ISSUE TITLE
Helmsman cannot remove release with target flag

### ISSUE THREAD

**Issue by ruanda** [Praqma/helmsman#648]
Helmsman cannot remove release in cluster under following conditions:
* target flag is used (with yaml key as a value)
* release name (`name` field) is different then yaml key

eg.
```
apps:
  ldap-gateway:
    enabled: false
    wait: true
    timeout: 300
    namespace: "apps"
    chart: "charts/X"
    version: "0.2.0"
    name: "ldap"
    secretsFiles:
      - "X.yaml"
```

when run with `-target ldap-gateway` it does not find any release and do nothing.
