### ISSUE TITLE
App tillerNamespace ignored

### ISSUE THREAD

**Issue by kiddo3** [Praqma/helmsman#71]
I'm trying to deploy the app nginx using a tiller in namespace 'test', but helmsman is using tiller in namespace kube-system.
**My configuration**
namespaces section:
```yaml
namespaces:
  test:
    installTiller: false
    protected: false
  kube-system:
    installTiller: false
```

Apps section:
```yaml
apps:
  nginx:
    chart: stable/nginx-ingress
    enabled: true
    name: nginx
    namespace: test
    tillerNamespace: test
    valuesFile: helm-values/nginx_values.yaml
    version: 0.28.1
    wait: true
```
Output without apply:
```bash
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_|version: v1.5.0
A Helm-Charts-as-Code tool.


2018/09/05 09:35:14 INFO: Parsed YAML [[ deploy.yaml ]] successfully and found [ 2 ] apps.
2018/09/05 09:35:14 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ test ].
2018/09/05 09:35:14 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ kube-system ].
2018/09/05 09:35:14 ERROR: apps validation failed -- for app [nginx ]. app is desired to be deployed using Tiller from [[ kube-system ]] but kube-system is not desired to have a Tiller. You can use another Tiller with the 'tillerNamespace' option or deploy Tiller in kube-system.
```

**Comment by sami-alajrami** [comment]
@kiddo3 your desired state does not want Tiller in `test` namespace.  Since you define its `installTiller: false`

Changing it to true will let helmsman deploy with Tiller from `test`. If you already deployed Tiller in the test namespace manually, helmsman does not see that. Enabling it to install Tiller there will simply upgrade Tiller to whichever helm client version you are running. 

```yaml
namespaces:
  test:
    installTiller: true
  ...
```

**Comment by kiddo3** [comment]
Thanks @sami-alajrami 
In my opinion I think it would be great that the installation of tiller become optional and not mandatorily be managed by helmsman.

**Comment by rsanders** [comment]
We manually install Tiller due to local preferences in configuration. `installTiller` appears to also mean `useTiller`, but they would be must useful to us if separate concepts.

**Comment by grrywlsn** [comment]
+1 for clarifying. We're specifying `installTiller = true` even though we know tiller is already installed in the namespace, just so that we can enable `tillerNamespace` in the app definition.

**Comment by luisdavim** [comment]
@rsanders what's the difference between the way you install tiller manually and the way helmsman installs it? In other words,  why not just let helmsman manage all tiller installations?

**Comment by sami-alajrami** [comment]
@rsanders @kiddo3  may I know what options do you use for deploying Tiller ? we might add them as options within helmsman Tiller deployment if relevant :) 

For the time being, a `useTiller` flag should be easy to add.

**Comment by sami-alajrami** [comment]
you can now use `useTiller: true` with your namespaces. This tells helmsman not to deploy Tiller there. Helmsman will still run a check to verify that Tiller is ready in that namespace. Then it deploys releases to it.
This option can't be used together with `installTiller` obviously. 
I only recommend using it when you have special deployment for your Tiller that helmsman doesn't currently support.

example: 
```yaml
namespaces:
  test:
    useTiller: true
  kube-system:
    installTiller: false
```
