### ISSUE TITLE
YAML anchors fail on "duplicate" keys

### ISSUE THREAD

**Issue by flypenguin** [Praqma/helmsman#711]
# actual behavior

i have the (shortened) `helmsman.yaml` file i pasted below, one line in the apps template marked with "THE CRITICAL LINE". now, if i leave that line _in_, i get this error message when executing helmsman:

```bash
$ helmsman -f helmsman.yaml
2022-09-13 11:55:46 CRITICAL: error building the state from files: error converting YAML to JSON: yaml: unmarshal errors:
  line 111: key "description" already set in map
```

that is also very much not what should happen according to the [linked page](https://blog.daemonl.com/2016/02/yaml.html) in [your docs](https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md#appstemplates).

# expected behavior

helmsman should execute, using the description from the actual app chart.

# the config file

```yaml

appsTemplates:
  .gitlab-runner: &gitlab-runner
    chart: "gitlab/gitlab-runner"
    description: "A GitLab runner" # THE CRITICAL LINE
    enabled: true
    namespace: gitlab
    version: 0.44.0
    group: gitlab

apps:
  gitlab-runner:
    <<: *gitlab-runner
    description: "Gitlab runner used for CI/CD"
    name: "gitlab-runner"
    valuesFile: "values-gitlab-runner.yaml"
```
