### ISSUE TITLE
Hooks manifests should support encryption/decryption

### ISSUE THREAD

**Issue by mkubaczyk** [Praqma/helmsman#757]
Hooks implementation should support encryption/decryption of values (helm-secrets, hiera-eyaml depending on the settings) in the manifests file.

```---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-key
data:
  my-key.json: <base64 of JSON key> 
```
I'd like to be able to encrypt value of `my-key.json` because it contains sensitive value I'd not like to store in plain text in repo.

This may require some change in the way hooks are defined or we can try with additional key like:
```
hooks:
  encrypted: true
  preInstall: "../values/hooks/secrets.yaml"
  [...]
```
to force decryption of the files defined for hooks.
