### ISSUE TITLE
Priority cannot be configured for files in spec

### ISSUE THREAD

**Issue by Sheludchenko** [Praqma/helmsman#780]
I tried to split a long file into multiple ones. I used this document **docs/how_to/misc/multiple_desired_state_files_specification.md** as a reference.

Here's a sample spec file I'm trying to use:
```
---
stateFiles:
 - path: common.yaml
   priority: -20
 - path: crd.yaml
   priority: -10
 - path: service.yaml
   priority: 0
```

Here's a command I'm trying to run:
```
helmsman --spec environment.spec.yaml --dry-run --no-fancy
```

Here's an error I'm getting:
```
2023-03-30 14:42:55 CRITICAL: error parsing spec file: yaml: unmarshal errors:
  line 4: field priority not found in type app.StatePath
```

I looked through **internal/app/spec_state.go** and didn't find any reference for **priority** field.
