### ISSUE TITLE
helmsman support multi port values????

### ISSUE THREAD

**Issue by Nurlan199206** [Praqma/helmsman#875]
how to make multiple ports in service???

it's my example

```
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  port: 8446
  targetPort: 8446
  port: 8083
```
