### ISSUE TITLE
Wrong values file path when apply ugprade

### ISSUE THREAD

**Issue by qiuyuzhou** [Praqma/helmsman#93]
Pass plan stage then failed to apply.
Please look at last two lines.

![image](https://user-images.githubusercontent.com/2310221/46157551-92ee7800-c2ae-11e8-8504-03b7d396a7a6.png)

```
Charlie-MBP-2018:elk qiuyuzhou$ helmsman --apply -f elk.yaml --verbose
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.6.1
A Helm-Charts-as-Code tool.


2018/09/27 23:25:39 VERBOSE: kubectl client version: v1.11.3
2018/09/27 23:25:39 VERBOSE: Helm client version: v2.11.0+g2e55dbe
2018/09/27 23:25:39 INFO: Parsed YAML [[ elk.yaml ]] successfully and found [ 2 ] apps.
2018/09/27 23:25:39 INFO: namespace validation -- a pre-installed Tiller is desired to be used in namespace [ kube-system ].
2018/09/27 23:25:39 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ elk ].
2018/09/27 23:25:39 VERBOSE: kubectl config use-context kubernetes-admin-c5ebb1bcc4f954c5aa55826969ed6282a
2018/09/27 23:25:39 VERBOSE: kubectl create namespace elk
2018/09/27 23:25:39 WARN: I could not create namespace [elk ]. It already exists. I am skipping this.
2018/09/27 23:25:39 VERBOSE: kubectl create namespace kube-system
2018/09/27 23:25:39 WARN: I could not create namespace [kube-system ]. It already exists. I am skipping this.
2018/09/27 23:25:39 VERBOSE: helm list --tiller-namespace kube-system
2018/09/27 23:25:40 VERBOSE: helm repo add stable https://charts.shundaojia.com/stable
2018/09/27 23:25:41 VERBOSE: helm repo add incubator https://charts.shundaojia.com/incubator
2018/09/27 23:25:41 VERBOSE: helm repo update
2018/09/27 23:25:42 VERBOSE: helm search incubator/elasticsearch --version 1.8.1 -l
2018/09/27 23:25:43 VERBOSE: helm search stable/kibana --version 0.14.5 -l
2018/09/27 23:25:43 INFO: checking what I need to do for your charts ...
2018/09/27 23:25:43 INFO: mapping the current helm state ...
2018/09/27 23:25:43 VERBOSE: helm list --all --max 0 --output json --tiller-namespace kube-system
2018/09/27 23:25:44 VERBOSE: helm diff upgrade elasticsearch incubator/elasticsearch -f /Users/qiuyuzhou/Develop_Work/k8s-ali/elk/./values/elasticsearch-values.yaml --version 1.8.1  --tiller-namespace kube-system
elk, elasticsearch-master, StatefulSet (apps) has changed:
  # Source: elasticsearch/templates/master-statefulset.yaml
  apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      app: elasticsearch
      chart: elasticsearch-1.8.1
      component: "master"
      heritage: Tiller
      release: elasticsearch
    name: elasticsearch-master
  spec:
    serviceName: elasticsearch-master
    replicas: 3
    template:
      metadata:
        labels:
          app: elasticsearch
          component: "master"
          release: elasticsearch
      spec:
        securityContext:
          fsGroup: 1000
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: "elasticsearch"
                    release: "elasticsearch"
                    component: "master"
        initContainers:
        # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
        # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
        - name: "sysctl"
          image: "busybox"
          imagePullPolicy: "Always"
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: "chown"
          image: "registry-hk.docker.shundaojia.com/elasticsearch/elasticsearch:6.4.1"
          imagePullPolicy: "IfNotPresent"
          command:
          - /bin/bash
          - -c
          - chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data &&
            chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/logs
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
        containers:
        - name: elasticsearch
          env:
          - name: NODE_DATA
            value: "false"
          - name: DISCOVERY_SERVICE
            value: elasticsearch-discovery
          - name: PROCESSORS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
          - name: ES_JAVA_OPTS
            value: "-Djava.net.preferIPv4Stack=true -Xms512m -Xmx512m"
          - name: MINIMUM_MASTER_NODES
            value: "2"
          - name: XPACK_MONITORING_ENABLED
            value: "true"
          resources:
              limits:
                cpu: "1"
              requests:
                cpu: 25m
                memory: 512Mi

          readinessProbe:
            httpGet:
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          image: "registry-hk.docker.shundaojia.com/elasticsearch/elasticsearch:6.4.1"
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 9300
            name: transport

          - containerPort: 9200
            name: http

          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
          - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            name: config
            subPath: elasticsearch.yml
        volumes:
        - name: config
          configMap:
            name: elasticsearch
    updateStrategy:
      type: OnDelete
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "alicloud-disk-ssd"
        resources:
          requests:
-           storage: "4Gi"
+           storage: "20Gi"

2018/09/27 23:25:45 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2018/09/27 23:25:45 VERBOSE: kubectl get configmap -n kube-system -l MANAGED-BY=HELMSMAN
2018/09/27 23:25:45 VERBOSE: kubectl get configmap -n kube-system -l MANAGED-BY=HELMSMAN
2018/09/27 23:25:45 INFO: no untracked releases found.
2018/09/27 23:25:45 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2018/09/27 23:25:45 INFO: Plan generated at: Thu Sep 27 2018 15:25:43
DECISION: release [ elasticsearch ] is desired to be enabled and is currently enabled. I will upgrade it! -- priority: 0
DECISION: release [ kibana ] is set to be disabled but is not yet deployed. Skipping. -- priority: 0
2018/09/27 23:25:45 INFO: sorting the commands in the plan based on priorities (order flags) ...
2018/09/27 23:25:45 INFO: Executing the plan ...
2018/09/27 23:25:45 VERBOSE: helm upgrade elasticsearch incubator/elasticsearch -f /Users/qiuyuzhou/Develop_Work/k8s-ali/elk/.//Users/qiuyuzhou/Develop_Work/k8s-ali/elk/./values/elasticsearch-values.yaml --version 1.8.1 --force  --tiller-namespace kube-system
2018/09/27 23:25:46 Command returned with exit code: . And error message: Error: open /Users/qiuyuzhou/Develop_Work/k8s-ali/elk/.//Users/qiuyuzhou/Develop_Work/k8s-ali/elk/./values/elasticsearch-values.yaml: no such file or directory    
```

**Comment by sami-alajrami** [comment]
@qiuyuzhou could you please share your desired state file?

**Comment by qiuyuzhou** [comment]
```
# metadata -- add as many key/value pairs as you want
metadata:
  org: "shundaojia.com"
  maintainer: "charlie@shundaojia.com"
  description: "Elastic Stack"

settings:
  kubeContext: "kubernetes-admin-c5ebb1bcc4f954c5aa55826969ed6282a"
  # storageBackend: "secret" # default is configMap

namespaces:
  kube-system:
    useTiller: true
  elk:
    protected: false
    installTiller: false

helmRepos:
  stable: "https://charts.shundaojia.com/stable"
  incubator: "https://charts.shundaojia.com/incubator"

apps:
  elasticsearch:
    namespace: "elk"
    enabled: true
    chart: "incubator/elasticsearch"
    version: "1.8.1"
    valuesFiles:
      - "values/elasticsearch-values.yaml"

  kibana:
    namespace: "elk"
    enabled: false
    chart: "stable/kibana"
    version: "0.14.5"
    valuesFiles:
      - "values/kibana-values.yaml"
```

**Comment by sami-alajrami** [comment]
@qiuyuzhou this is a bug when you use `valuesFiles`  note the (s). Since you are only using one values file. The quick fix is to use `valuesFile` instead of `valuesFiles` : 

```yaml
apps:
  elasticsearch:
    namespace: "elk"
    enabled: true
    chart: "incubator/elasticsearch"
    version: "1.8.1"
    valuesFile: "values/elasticsearch-values.yaml"

  kibana:
    namespace: "elk"
    enabled: false
    chart: "stable/kibana"
    version: "0.14.5"
    valuesFile: "values/kibana-values.yaml"
```
